WPN_NO_SEC = [["","",0,0]];
WPN_NO_GREN = "";
WPN_GRENADE_W = "HandGrenade_West";
WPN_GRENADE_E = "HandGrenade_East";
WPN_M9 = ["m9","15Rnd_9x19_M9",1,8];
WPN_M9SD = ["m9SD","15Rnd_9x19_M9SD",1,8];
WPN_G17 = ["glock17_EP1","17Rnd_9x19_glock17",1,8];
WPN_PDW = ["UZI_EP1","30Rnd_9x19_UZI",1,8];
WPN_MAKAROV = ["makarov","8Rnd_9x18_Makarov",1,8];
WPN_MAKAROV_SD = ["makarovSD","8Rnd_9x18_MakarovSD",1,8];
WPN_SKORPION = ["Sa61_EP1","20Rnd_B_765x17_Ball",1,8];
WPN_M1911 = ["Colt1911","7Rnd_45ACP_1911",1,8];

WPN_M16A4 = ["m16a4","30Rnd_556x45_Stanag"];
WPN_M4AIM = ["M4A1_Aim","30Rnd_556x45_Stanag"];
WPN_M4A1 = ["M4A1","30Rnd_556x45_Stanag"];
WPN_M249 = ["M249","200Rnd_556x45_M249"];
WPN_M249B = ["M249_EP1","100Rnd_556x45_M249"];
WPN_M249SCOPE = ["M249_m145_EP1","100Rnd_556x45_M249"];
WPN_M249TIS = ["M249_TWS_EP1","100Rnd_556x45_M249"];
WPN_M240 = ["M240","100Rnd_762x51_M240"];
WPN_M240SCOPE = ["m240_scoped_EP1","100Rnd_762x51_M240"];
WPN_M14 = ["M14_EP1","20Rnd_762x51_DMR"];
WPN_M4CCO = ["M4A3_CCO_EP1","30Rnd_556x45_Stanag"];
WPN_M16A2 = ["M16A2","30Rnd_556x45_Stanag"];
WPN_SA80SUSAT = ["BAF_L85A2_RIS_SUSAT","30Rnd_556x45_Stanag"];
WPN_SA80ACOG = ["BAF_L85A2_RIS_ACOG","30Rnd_556x45_Stanag"];
WPN_SA80AWS = ["BAF_L85A2_RIS_CWS","30Rnd_556x45_Stanag"];
WPN_LSW = ["BAF_L86A2_ACOG","30Rnd_556x45_Stanag"];
WPN_L110 = ["BAF_L110A1_Aim","100Rnd_556x45_M249"];
WPN_GPMG = ["BAF_L7A2_GPMG","100Rnd_762x51_M240"];
WPN_SA58CCO = ["Sa58V_CCO_EP1","30Rnd_762x39_SA58"];
WPN_SA58ACOG = ["Sa58V_RCO_EP1","30Rnd_762x39_SA58"];
WPN_M4AIM_SD = ["M4A1_AIM_SD_camo","30Rnd_556x45_StanagSD"];
WPN_M60 = ["M60A4_EP1","100Rnd_762x51_M240"];
WPN_AKM = ["AK_47_M","30Rnd_762x39_AK47"];
WPN_AKS = ["AK_47_S","30Rnd_762x39_AK47"];
WPN_FAL = ["FN_FAL","20Rnd_762x51_FNFAL"];
WPN_LEE = ["LeeEnfield","10x_303"];
WPN_PK = ["PK","100Rnd_762x54_PK"];
WPN_SVD = ["SVD","10Rnd_762x54_SVD"];
WPN_AK74 = ["AK_74","30Rnd_545x39_AK"];
WPN_AKS74 = ["AKS_74","30Rnd_545x39_AK"];
WPN_AKSU74 = ["AKS_74_U","30Rnd_545x39_AK"];
WPN_AKS74PSO = ["AKS_74_pso","30Rnd_545x39_AK"];
WPN_AKS74KOBRA = ["AKS_74_kobra","30Rnd_545x39_AK"];
WPN_M24DES = ["M24_des_EP1","5Rnd_762x51_M24"];
WPN_M107 = ["m107","10Rnd_127x99_m107"];
WPN_M107TIS = ["m107_TWS_EP1","10Rnd_127x99_m107"];
WPN_M110NV = ["M110_NVG_EP1","20Rnd_762x51_B_SCAR"];
WPN_M110TIS = ["M110_TWS_EP1","20Rnd_762x51_B_SCAR"];
WPN_SVD_CAMO_DES = ["SVD_des_EP1","10Rnd_762x54_SVD"];
WPN_SVD_NPSU = ["SVD_NSPU_EP1","10Rnd_762x54_SVD"];
WPN_AKS74_NSPU = ["AKS_74_NSPU","30Rnd_545x39_AK"];
WPN_AKS74_TIS = ["AKS_74_GOSHAWK","30Rnd_545x39_AK"];
WPN_LRR = ["BAF_LRR_scoped_W","5Rnd_86x70_L115A1"];
WPN_AS50 = ["BAF_AS50_scoped","5Rnd_127x99_as50"];
WPN_AS50TIS = ["BAF_AS50_TWS","5Rnd_127x99_as50"];
WPN_M17 = ["SCAR_H_CQC_CCO","20Rnd_762x51_B_SCAR"];
WPN_M17GL = ["SCAR_H_STD_EGLM_Spect","20Rnd_762x51_B_SCAR","1Rnd_HE_M203"];
WPN_M17SNIPER = ["SCAR_H_LNG_Sniper","20Rnd_762x51_B_SCAR"];
WPN_M17SD = ["SCAR_H_CQC_CCO_SD","20Rnd_762x51_SB_SCAR"];
WPN_M17TISSD = ["SCAR_H_STD_TWS_SD","20Rnd_762x51_SB_SCAR"];
WPN_M17SNIPERSD = ["SCAR_H_LNG_Sniper_SD","20Rnd_762x51_SB_SCAR"];
WPN_G36A_CAMO = ["G36A_camo","30Rnd_556x45_G36"];
WPN_MG36_CAMO = ["MG36_camo","100Rnd_556x45_BetaCMag"];


WPN_AK74GL = ["AK_74_GL","30Rnd_545x39_AK","1Rnd_HE_GP25"];
WPN_SA80UGL = ["BAF_L85A2_UGL_SUSAT","30Rnd_556x45_Stanag","1Rnd_HE_M203"];
WPN_M16A2GL = ["M16A2GL","30Rnd_556x45_Stanag","1Rnd_HE_M203"];
WPN_M16A4GL = ["M16A4_GL","30Rnd_556x45_Stanag","1Rnd_HE_M203"];

WPN_M136 = ["M136","M136",6,1];
WPN_MAAWS = ["MAAWS","MAAWS_HEDP",3,2];
WPN_MAAWS2 = ["MAAWS","MAAWS_HEAT",3,2];
WPN_JAV = ["Javelin","Javelin",6,1];
WPN_NLAW = ["BAF_NLAW_Launcher","NLAW",3,2];
WPN_RPG = ["RPG7V","PG7V",2,3];
WPN_RPGL = ["RPG7V","PG7VL",2,3];
WPN_RPGR = ["RPG7V","PG7VR",3,2];
WPN_RPGO = ["RPG7V","OG7",2,3];
WPN_DRAGON = ["M47Launcher_EP1","Dragon_EP1",6,1];
WPN_STING = ["Stinger","Stinger",6,1];
WPN_STRELA = ["Strela","Strela",6,1];
WPN_AT13 = ["MetisLauncher","AT13",6,1];

WPN_M4AIM_CAMO = ["M4A1_AIM_CAMO","30Rnd_556x45_Stanag"];
WPN_M4AIM_CAMO_SD = ["M4A1_AIM_SD_camo","30Rnd_556x45_StanagSD"];
WPN_MK48 = ["MK_48","100Rnd_762x51_M240"];
WPN_DMR = ["DMR","20Rnd_762x51_DMR"];
WPN_PK_SCOPE = ["Pecheneg","100Rnd_762x54_PK"];
WPN_RPK = ["RPK_74","75Rnd_545x39_RPK"];
WPN_SVD_CAMO = ["SVD_Camo","10Rnd_762x54_SVD"];
WPN_KSVK = ["ksvk","5Rnd_127x108_KSVK"];
WPN_VSS = ["VSS_Vintorez","20Rnd_9x39_SP5_VSS"];
WPN_AK74 = ["AK_74","30Rnd_545x39_AK"];
WPN_AKSU74 = ["AKS_74_U","30Rnd_545x39_AK"];
WPN_AKS74_PSO = ["AKS_74_pso","30Rnd_545x39_AK"];
WPN_AKS74KOBRA = ["AKS_74_kobra","30Rnd_545x39_AK"];
WPN_M40 = ["M40A3","5Rnd_762x51_M24"];
WPN_AK107 = ["AK_107_Kobra","30Rnd_545x39_AK"];
WPN_AK107_SCOPE = ["AK_107_PSO","30Rnd_545x39_AK"];
WPN_AKS74KOBRA_SD = ["AKS_74_UN_Kobra","30Rnd_545x39_AKSD"];
WPN_BIZON = ["Bizon","64Rnd_9x19_Bizon"];
WPN_BIZON_SD = ["Bizon_Silenced","64Rnd_9x19_SD_Bizon"];
WPN_AK107GL_SCOPE = ["AK_107_GL_PSO","30Rnd_545x39_AK","1Rnd_HE_GP25"];
WPN_AK107GL = ["AK_107_GL_Kobra","30Rnd_545x39_AK","1Rnd_HE_GP25"];
WPN_M4HOLO_CAMO = ["M4A1_HWS_GL_CAMO","30Rnd_556x45_Stanag","1Rnd_HE_M203"];
WPN_M4HOLO_CAMO_SD = ["M4A1_HWS_GL_SD_Camo","30Rnd_556x45_StanagSD","1Rnd_HE_M203"];
WPN_SMAW = ["SMAW","SMAW_HEAA",2,3];
WPN_SMAW2 = ["SMAW","SMAW_HEDP",2,3];
WPN_RPG18 = ["RPG18","RPG18",6,1];
WPN_IGLA = ["Igla","Igla",6,1];

//----czech weapons----
WPN_SA58CCO = ["Sa58V_CCO_EP1","30Rnd_762x39_SA58"];
WPN_SA58ACOG = ["Sa58V_RCO_EP1","30Rnd_762x39_SA58"];
WPN_SA58V = ["Sa58V_EP1","30Rnd_762x39_SA58"];
WPN_M4AIM_SD = ["M4A1_AIM_SD_camo","30Rnd_556x45_StanagSD"];
WPN_M60 = ["M60A4_EP1","100Rnd_762x51_M240"];
//acr addon weapons
WPN_CZ805A1 = ["CZ805_A1_ACR","30Rnd_556x45_G36"];
WPN_CZ805A1GL = ["CZ805_A1_GL_ACR","30Rnd_556x45_G36","1Rnd_HE_M203"];
WPN_CZ805A2 = ["CZ805_A2_ACR","30Rnd_556x45_G36"];
WPN_CZ805BGL = ["CZ805_B_GL_ACR","20Rnd_762x51_B_SCAR","1Rnd_HE_M203"];
WPN_UK59 = ["UK59_ACR","100Rnd_762x54_PK"];
WPN_CZ750 = ["CZ_750_S1_ACR","10Rnd_762x51_CZ750"];
WPN_CZ75_C = ["CZ_75_D_COMPACT","10Rnd_9x19_Compact",1,8];
WPN_CZ75_D = ["CZ_75_P_07_DUTY","15Rnd_9x19_M9",1,8];
WPN_CZ75_P = ["CZ_75_SP_01_PHANTOM","18Rnd_9x19_Phantom",1,8];
WPN_CZ75_P_SD = ["CZ_75_SP_01_PHANTOM_SD","18Rnd_9x19_PhantomSD",1,8];

WPNS_BINO = ["Binocular"];
WPNS_NVG = ["NVGoggles"];
WPNS_NVG_RF = ["NVGoggles","Binocular_Vector"];
WPNS_NVG_BINO = ["NVGoggles","Binocular"];

SMOKE_TYPES = ["smokeshell","smokeshell","smokeshell","smokeshell","smokeshell","smokeshell"];
SMOKE_TYPES = SMOKE_TYPES + ["smokeShellRed","smokeShellGreen","smokeShellBlue","SmokeShellYellow","SmokeShellPurple","SmokeShellOrange"];


//---- United States Marine Corps ----

US_AMMOS = [6,7,8];
US_GRENS = [2,3,4];
US_RIFLES = [WPN_M16A4];
US_MGS = [WPN_M249,WPN_M240];
US_ATS = [WPN_M136,WPN_SMAW,WPN_SMAW2,WPN_JAV];
US_SNIPERRIFLES = [WPN_M40,WPN_M107];

US_SOLDIERS = ["USMC_Soldier"];

US_MAN = [US_SOLDIERS,US_RIFLES+[WPN_M16A4GL,WPN_M16A4GL,WPN_DMR],WPN_NO_SEC,WPN_GRENADE_W,US_AMMOS,US_GRENS,WPNS_NVG];
US_MAN_MG = [US_SOLDIERS,US_MGS,WPN_NO_SEC,WPN_GRENADE_W,[5],[2],WPNS_NVG];
US_MAN_AT = [US_SOLDIERS,US_RIFLES,US_ATS,WPN_GRENADE_W,[5],[1],WPNS_NVG];
US_MAN_AA = [US_SOLDIERS,US_RIFLES,[WPN_STING],WPN_NO_GREN,US_AMMOS,US_GRENS,WPNS_NVG];
US_MAN_MEDIC = [["USMC_Soldier_Medic"],[WPN_M4AIM],WPN_NO_SEC,"SmokeShell",[5],[3],WPNS_NVG];
US_MAN_DRIVER = [US_SOLDIERS,[WPN_M4A1],WPN_NO_SEC,WPN_GRENADE_W,[4,5,6],[0,1,2],WPNS_NVG];
US_MAN_TANK_CREW = [["USMC_Soldier_Crew"],[WPN_M4A1],WPN_NO_SEC,WPN_GRENADE_W,[4,5,6],[0,1,2],WPNS_NVG];
US_MAN_PILOT = [["USMC_Soldier_Pilot"],[WPN_M4A1],WPN_NO_SEC,"SmokeShell",US_AMMOS,US_GRENS,WPNS_NVG];
US_MAN_SNIPER = [["USMC_SoldierS_Sniper"],US_SNIPERRIFLES,[WPN_M9],"SmokeShell",[8],US_GRENS,WPNS_NVG_BINO];
US_MAN_SPOTTER = [["USMC_SoldierS_Sniper"],[WPN_M16A4,WPN_M16A4GL],WPN_NO_SEC,WPN_GRENADE_W,US_AMMOS,US_GRENS,WPNS_NVG_BINO];
US_MAN_RECON = [["FR_GL"],[WPN_M4AIM_CAMO,WPN_M4HOLO_CAMO,WPN_DMR],[WPN_M9],WPN_GRENADE_W,[8],[4],WPNS_NVG_BINO];
US_MAN_RECON_MG = [["FR_GL"],[WPN_MK48],[WPN_M9],WPN_GRENADE_W,[5],[2],WPNS_NVG_BINO];
US_MAN_RECON_SD = [["FR_GL"],[WPN_M4AIM_CAMO_SD,WPN_M4HOLO_CAMO_SD],[WPN_M9SD],WPN_GRENADE_W,[8],[4],WPNS_NVG_BINO];

US_SQUAD = [6,10,
	US_MAN,US_MAN,US_MAN,US_MAN,US_MAN,US_MAN,US_MAN,US_MAN,
	US_MAN_MG,US_MAN_MG,
	US_MAN_AT,US_MAN_AT,
	US_MAN_AA,
	US_MAN_MEDIC
];

US_AT_TEAM = [3,5,US_MAN_AT];

US_RECON_TEAM = [4,8,
	US_MAN_RECON,US_MAN_RECON,US_MAN_RECON,
	US_MAN_RECON_MG
];

US_RECON_TEAM_SD = [4,8,US_MAN_RECON_SD];

usTeams = [
	US_SQUAD,US_SQUAD,US_SQUAD,US_SQUAD,US_SQUAD,US_SQUAD,
	US_AT_TEAM,US_AT_TEAM,
	US_RECON_TEAM,
	US_RECON_TEAM_SD
];

usSnipers = [[US_MAN_SNIPER,US_MAN_SPOTTER]];

_US_VEH_AMMOS = [
	"30Rnd_556x45_Stanag",
	"handgrenade_west",
	"200Rnd_556x45_M249",
	"100Rnd_762x51_M240",
	"1Rnd_HE_M203",
	"smaw_hedp",
	"smaw_heaa",
	"m136",
	"pipebomb",
	"10Rnd_127x99_m107",
	"5Rnd_762x51_M24",
	"20Rnd_762x51_DMR",
	"mine",
	"javelin",
	"stinger"
];

usCars = [
	["HMMWV",US_MAN_DRIVER,US_SQUAD,[],_US_VEH_AMMOS],
	["HMMWV_M2",US_MAN_DRIVER,US_SQUAD,[],_US_VEH_AMMOS],
	["HMMWV_Armored",US_MAN_DRIVER,US_SQUAD,[],_US_VEH_AMMOS],
	["HMMWV_MK19",US_MAN_DRIVER,US_SQUAD,[],_US_VEH_AMMOS],
	["HMMWV_TOW",US_MAN_DRIVER,US_SQUAD,[],_US_VEH_AMMOS],
	["MTVR",US_MAN_DRIVER,US_SQUAD,[],_US_VEH_AMMOS]
];

usArm = [
	["AAV",US_MAN_TANK_CREW,US_SQUAD,[],_US_VEH_AMMOS],
	["LAV25",US_MAN_TANK_CREW,US_SQUAD,[],_US_VEH_AMMOS],
	["M1A1",US_MAN_TANK_CREW,US_SQUAD,[],[]],
	["M1A2_TUSK_MG",US_MAN_TANK_CREW,US_SQUAD,[[0,1]],[]]
];

usHelis = [["AH64D",US_MAN_PILOT],["AH1Z",US_MAN_PILOT],["UH1Y",US_MAN_PILOT],["MH60S",US_MAN_PILOT]];

usAir = [["A10",US_MAN_PILOT],["AV8B2",US_MAN_PILOT],["F35B",US_MAN_PILOT]];

US_PLAYER_PISTOLS = WPN_NO_SEC+WPN_NO_SEC+[WPN_M9,WPN_M9,WPN_M9,WPN_M9SD];
usPLIST = [
	[west,[US_SOLDIERS,[WPN_M16A4],US_PLAYER_PISTOLS,WPN_GRENADE_W,US_AMMOS,US_GRENS,WPNS_NVG],"USMC Soldier M16A4"],
	[west,[US_SOLDIERS,[WPN_M16A2],US_PLAYER_PISTOLS,WPN_GRENADE_W,US_AMMOS,US_GRENS,WPNS_NVG],"USMC Soldier M16A2"],
	[west,[US_SOLDIERS,[WPN_M4A1],US_PLAYER_PISTOLS,WPN_GRENADE_W,US_AMMOS,US_GRENS,WPNS_NVG],"USMC Soldier M4A1"],
	[west,[US_SOLDIERS,[WPN_M4AIM],US_PLAYER_PISTOLS,WPN_GRENADE_W,US_AMMOS,US_GRENS,WPNS_NVG],"USMC Soldier M4A1 AIM"],
	[west,[US_SOLDIERS,[WPN_M16A4GL],WPN_NO_SEC,WPN_GRENADE_W,US_AMMOS,US_GRENS,WPNS_NVG],"USMC Soldier M16A4 M203"],
	[west,[US_SOLDIERS,[WPN_M16A2GL],WPN_NO_SEC,WPN_GRENADE_W,US_AMMOS,US_GRENS,WPNS_NVG],"USMC Soldier M16A2 M203"],
	[west,[US_SOLDIERS,[WPN_DMR],US_PLAYER_PISTOLS,WPN_GRENADE_W,US_AMMOS,US_GRENS,WPNS_NVG],"USMC Marksman DMR"],
	[west,[US_SOLDIERS,[WPN_M249],US_PLAYER_PISTOLS,WPN_GRENADE_W,[5],[2],WPNS_NVG],"USMC Machinegunner M249"],
	[west,[US_SOLDIERS,[WPN_M240],US_PLAYER_PISTOLS,WPN_GRENADE_W,[5],[2],WPNS_NVG],"USMC Machinegunner M240"],
	[west,[US_SOLDIERS,[WPN_M16A4],[WPN_M136],WPN_GRENADE_W,[5],[1],WPNS_NVG],"USMC AT Soldier M136"],
	[west,[US_SOLDIERS,[WPN_M16A4],[WPN_SMAW],WPN_GRENADE_W,[5],[1],WPNS_NVG],"USMC AT Soldier SMAW AT"],
	[west,[US_SOLDIERS,[WPN_M16A4],[WPN_SMAW2],WPN_GRENADE_W,[5],[1],WPNS_NVG],"USMC AT Soldier SMAW HEDP"],
	[west,[US_SOLDIERS,[WPN_M16A4],[WPN_JAV],WPN_GRENADE_W,[5],[1],WPNS_NVG],"USMC AT Soldier Javelin"],
	[west,[US_SOLDIERS,[WPN_M16A4],[WPN_STING],WPN_GRENADE_W,[5],[1],WPNS_NVG],"USMC AA Soldier"],
	[west,[["USMC_Soldier_Medic"],[WPN_M4AIM],WPN_NO_SEC,"SmokeShell",[5],[3],WPNS_NVG],"USMC Medic"],
	[west,[["FR_GL"],[WPN_M4AIM_CAMO],[WPN_M9],WPN_GRENADE_W,[8],[4],WPNS_NVG_BINO],"Force Recon Soldier M4 AIM Camo"],
	[west,[["FR_GL"],[WPN_M4HOLO_CAMO],WPN_NO_SEC,WPN_GRENADE_W,[8],[4],WPNS_NVG_BINO],"Force Recon Soldier M4 HOLO Camo M203"],
	[west,[["FR_GL"],[WPN_DMR],[WPN_M9],WPN_GRENADE_W,[8],[4],WPNS_NVG_BINO],"Force Recon Marksman DMR"],
	[west,[["FR_GL"],[WPN_MK48],[WPN_M9],WPN_GRENADE_W,[5],[2],WPNS_NVG_BINO],"Force Recon Machinegunner MK48"],
	[west,[["FR_GL"],[WPN_M4AIM_CAMO_SD],[WPN_M9SD],WPN_GRENADE_W,[8],[4],WPNS_NVG_BINO],"Force Recon Soldier M4 AIM Camo SD"],
	[west,[["FR_GL"],[WPN_M4HOLO_CAMO_SD],WPN_NO_SEC,WPN_GRENADE_W,[8],[4],WPNS_NVG_BINO],"Force Recon Soldier M4 HOLO Camo SD M203"],
	[west,[["USMC_SoldierS_Sniper"],[WPN_M40],[WPN_M9],"SmokeShell",[8],US_GRENS,WPNS_NVG_BINO],"USMC Sniper M40"],
	[west,[["USMC_SoldierS_Sniper"],[WPN_M107],[WPN_M9],"SmokeShell",[8],US_GRENS,WPNS_NVG_BINO],"USMC Sniper M107"]
];


//---- British Army, woodland DPM ----

BA_AMMOS = [6,7,8];
BA_GRENS = [2,3,4];
BA_RIFLES = [WPN_SA80SUSAT,WPN_SA80SUSAT,WPN_SA80SUSAT,WPN_SA80SUSAT];
BA_MGS = [WPN_L110,WPN_GPMG];
BA_ATS = [WPN_NLAW,WPN_NLAW,WPN_JAV];
BA_SNIPERRIFLES = [WPN_LRR,WPN_LRR,WPN_LRR,WPN_LRR,WPN_AS50,WPN_AS50TIS];

BA_SOLDIERS = ["BAF_Soldier_W"];

BA_MAN = [BA_SOLDIERS,BA_RIFLES+[WPN_SA80UGL,WPN_SA80ACOG,WPN_LSW,WPN_SA80AWS],WPN_NO_SEC,WPN_GRENADE_W,BA_AMMOS,BA_GRENS,WPNS_NVG];
BA_MAN_MG = [BA_SOLDIERS,BA_MGS,WPN_NO_SEC,WPN_GRENADE_W,[5],[0,1,2],WPNS_NVG];
BA_MAN_AT = [BA_SOLDIERS,[WPN_SA80SUSAT],BA_ATS,WPN_GRENADE_W,[5],[0,1],WPNS_NVG];
BA_MAN_AA = [BA_SOLDIERS,[WPN_SA80SUSAT],[WPN_STING],WPN_GRENADE_W,[5],[0,1],WPNS_NVG];
BA_MAN_MEDIC = [["BAF_Soldier_Medic_W"],[WPN_SA80SUSAT],WPN_NO_SEC,"SmokeShell",[5],[3],WPNS_NVG];
BA_MAN_TANK_CREW = [["BAF_crewman_W"],[WPN_SA80SUSAT],WPN_NO_SEC,WPN_GRENADE_W,[4,5,6],[0,1,2],WPNS_NVG];
BA_MAN_PILOT = [["BAF_Pilot_W"],[WPN_SA80SUSAT],WPN_NO_SEC,"SmokeShell",BA_AMMOS,BA_GRENS,WPNS_NVG];
BA_MAN_SNIPER = [["BAF_Soldier_Sniper_W"],BA_SNIPERRIFLES,[WPN_M9,WPN_PDW],"SmokeShell",[10],[2],WPNS_NVG_RF];
BA_MAN_SPOTTER = [["BAF_Soldier_Sniper_W"],[WPN_SA80UGL,WPN_SA80AWS],WPN_NO_SEC,WPN_GRENADE_W,BA_AMMOS,BA_GRENS,WPNS_NVG_RF];

BA_SQUAD = [6,10,
	BA_MAN,BA_MAN,BA_MAN,BA_MAN,BA_MAN,BA_MAN,BA_MAN,BA_MAN,
	BA_MAN_MG,BA_MAN_MG,
	BA_MAN_AT,BA_MAN_AT,
	BA_MAN_AA,
	BA_MAN_MEDIC
];

BA_AT_TEAM = [3,5,BA_MAN_AT];

baTeams = [
	BA_SQUAD,BA_SQUAD,BA_SQUAD,BA_SQUAD,BA_SQUAD,BA_SQUAD,BA_SQUAD,BA_SQUAD,
	BA_AT_TEAM,BA_AT_TEAM
];

baSnipers = [[BA_MAN_SNIPER,BA_MAN_SPOTTER]];

_BA_VEH_AMMOS = [
	"30Rnd_556x45_Stanag",
	"handgrenade_west",
	"200Rnd_556x45_L110A1",
	"100Rnd_762x51_M240",
	"1Rnd_HE_M203",
	"NLAW",
	"javelin",
	"stinger",
	"pipebomb",
	"mine",
	"5Rnd_86x70_L115A1",
	"5Rnd_127x99_as50"
];

baCars = [];
baCars = baCars + [["BAF_Offroad_W",BA_MAN,BA_SQUAD,[],_BA_VEH_AMMOS]];
baCars = baCars + [["BAF_Jackal2_GMG_W",BA_MAN,BA_SQUAD,[],_BA_VEH_AMMOS]];
baCars = baCars + [["BAF_Jackal2_L2A1_W",BA_MAN,BA_SQUAD,[],_BA_VEH_AMMOS]];

baArm = [];
baArm = baArm + [["BAF_FV510_W",BA_MAN_TANK_CREW,BA_SQUAD,[],_BA_VEH_AMMOS]];

baHelis = [["BAF_Apache_AH1_W",BA_MAN_PILOT],["AW159_Lynx_BAF",BA_MAN_PILOT],["BAF_Merlin_HC3_W",BA_MAN_PILOT],["CH_47F_BAF",BA_MAN_PILOT]];

BA_PLAYER_PISTOLS = WPN_NO_SEC+WPN_NO_SEC+[WPN_M9,WPN_M9,WPN_M9,WPN_M9SD,WPN_M1911,WPN_M1911];

baPLIST = [
	[west,[BA_SOLDIERS,[WPN_SA80SUSAT],BA_PLAYER_PISTOLS,WPN_GRENADE_W,BA_AMMOS,BA_GRENS,WPNS_NVG],"British Army Soldier SA80 SUSAT"],
	[west,[BA_SOLDIERS,[WPN_SA80ACOG],BA_PLAYER_PISTOLS,WPN_GRENADE_W,BA_AMMOS,BA_GRENS,WPNS_NVG],"British Army Soldier SA80 ACOG"],
	[west,[BA_SOLDIERS,[WPN_SA80AWS],BA_PLAYER_PISTOLS,WPN_GRENADE_W,BA_AMMOS,BA_GRENS,WPNS_NVG],"British Army Soldier SA80 Thermal Scope"],
	[west,[BA_SOLDIERS,[WPN_SA80UGL],WPN_NO_SEC,WPN_GRENADE_W,BA_AMMOS,BA_GRENS,WPNS_NVG],"British Army Grenadier SA80 UGL"],
	[west,[BA_SOLDIERS,[WPN_LSW],BA_PLAYER_PISTOLS,WPN_GRENADE_W,BA_AMMOS,BA_GRENS,WPNS_NVG],"British Army Soldier LSW"],
	[west,[BA_SOLDIERS,[WPN_LRR],BA_PLAYER_PISTOLS,WPN_GRENADE_W,BA_AMMOS,BA_GRENS,WPNS_NVG],"British Army Marksman LRR"],
	[west,[BA_SOLDIERS,[WPN_L110],BA_PLAYER_PISTOLS,WPN_GRENADE_W,[4,5],[1,2],WPNS_NVG],"British Army Soldier LMG"],
	[west,[BA_SOLDIERS,[WPN_GPMG],BA_PLAYER_PISTOLS,WPN_GRENADE_W,[4,5],[1,2],WPNS_NVG],"British Army Machinegunner GPMG"],
	[west,[BA_SOLDIERS,[WPN_SA80SUSAT],[WPN_NLAW],WPN_GRENADE_W,[4,5],[0,1],WPNS_NVG],"British Army AT Soldier NLAW"],
	[west,[BA_SOLDIERS,[WPN_SA80SUSAT],[WPN_JAV],WPN_GRENADE_W,[4,5],[0,1],WPNS_NVG],"British Army AT Soldier Javelin"],
	[west,[BA_SOLDIERS,[WPN_SA80SUSAT],[WPN_STING],WPN_GRENADE_W,[4,5],[0,1],WPNS_NVG],"British Army AA Soldier Stinger"],
	[west,[["BAF_Soldier_Medic_W"],[WPN_SA80SUSAT],WPN_NO_SEC,"SmokeShell",[5],[3],WPNS_NVG],"British Army Medic"],
	[west,[["BAF_Soldier_Sniper_W"],[WPN_LRR],[WPN_M9,WPN_M9SD,WPN_M1911],"SmokeShell",[10],[2],WPNS_NVG_RF],"British Army Sniper LRR"],
	[west,[["BAF_Soldier_Sniper_W"],[WPN_AS50],[WPN_M9,WPN_M9SD,WPN_M1911],"SmokeShell",[10],[2],WPNS_NVG_RF],"British Army Sniper AS50"],
	[west,[["BAF_Soldier_Sniper_W"],[WPN_AS50TIS],[WPN_M9,WPN_M9SD,WPN_M1911],"SmokeShell",[10],[2],WPNS_NVG_RF],"British Army Sniper AS50 Thermal Scope"]
];


//---- Army of the Czech Republic (woodland)----
CZ_AMMOS = [6,7,8];
CZ_GRENS = [2,3,4];
CZ_RIFLES = [WPN_CZ805A1,WPN_CZ805A1,WPN_CZ805A1,WPN_CZ805A1GL];
CZ_MGS = [WPN_M249SCOPE,WPN_M60,WPN_UK59];
CZ_ATS = [WPN_RPGL,WPN_MAAWS,WPN_MAAWS2,WPN_JAV];

CZ_SOLDIERS = ["CZ_Soldier_Wdl_ACR"];
CZ_MAN = [CZ_SOLDIERS,CZ_RIFLES,WPN_NO_SEC,WPN_GRENADE_W,CZ_AMMOS,CZ_GRENS,WPNS_NVG];
CZ_MAN_MG = [CZ_SOLDIERS,CZ_MGS,WPN_NO_SEC,WPN_GRENADE_W,[5],[0,1,2],WPNS_NVG];
CZ_MAN_AT = [CZ_SOLDIERS,[WPN_CZ805A1],CZ_ATS,WPN_GRENADE_W,[5],[0,1],WPNS_NVG];
CZ_MAN_AA = [CZ_SOLDIERS,[WPN_CZ805A1],[WPN_STING],WPN_GRENADE_W,[5],[0,1],WPNS_NVG];
CZ_MAN_MEDIC = [["CZ_Soldier_Medic_Wdl_ACR"],[WPN_CZ805A2],WPN_NO_SEC,"SmokeShell",[5],[3],WPNS_NVG];
CZ_MAN_PILOT = [["CZ_Soldier_Pilot_Wdl_ACR"],[WPN_SA58V],WPN_NO_SEC,"SmokeShell",CZ_AMMOS,CZ_GRENS,WPNS_NVG];//pilots and crew now have SA58v
CZ_MAN_TANK_CREW = [["CZ_Soldier_Crew_Wdl_ACR"],[WPN_SA58V],WPN_NO_SEC,WPN_GRENADE_W,[4,5,6],[0,1,2],WPNS_NVG];
CZ_MAN_SNIPER = [["CZ_Soldier_Sniper_ACR"],[WPN_CZ750],[WPN_CZ75_P],"SmokeShell",[8],CZ_GRENS,WPNS_NVG_RF];//added acr cz750 sniper rifle
CZ_MAN_SPOTTER = [["CZ_Soldier_Sniper_ACR"],[WPN_CZ805A1GL],WPN_NO_SEC,"SmokeShell",CZ_AMMOS,CZ_GRENS,WPNS_NVG_RF];
CZ_MAN_SF = [["CZ_Soldier_Spec2_Wdl_ACR"],[WPN_CZ805BGL],[WPN_CZ75_P,WPN_CZ75_P_SD],WPN_GRENADE_W,[8],CZ_GRENS,WPNS_NVG_RF];
CZ_MAN_SF_MG = [["CZ_Soldier_Spec2_Wdl_ACR"],[WPN_M249SCOPE],[WPN_CZ75_P,WPN_CZ75_P_SD],WPN_GRENADE_W,[4],[0,1,2],WPNS_NVG_RF];
CZ_MAN_SF_AT = [["CZ_Soldier_Spec2_Wdl_ACR"],[WPN_CZ805BGL],[WPN_M136],WPN_GRENADE_W,[5],[0,1],WPNS_NVG_RF];
CZ_MAN_SF_MK = [["CZ_Soldier_Spec2_Wdl_ACR"],[WPN_CZ750],[WPN_CZ75_P],WPN_GRENADE_W,[8],CZ_GRENS,WPNS_NVG_RF];

CZ_SQUAD = [6,10,
	CZ_MAN,CZ_MAN,CZ_MAN,CZ_MAN,CZ_MAN,CZ_MAN,CZ_MAN,CZ_MAN,CZ_MAN,
	CZ_MAN_MG,CZ_MAN_MG,
	CZ_MAN_AT,CZ_MAN_AT,
	CZ_MAN_AA,
	CZ_MAN_MEDIC
];

CZ_AT_TEAM = [3,5,CZ_MAN_AT];

CZ_SF_TEAM = [4,8,
	CZ_MAN_SF,CZ_MAN_SF,CZ_MAN_SF,
	CZ_MAN_SF_MG,
	CZ_MAN_SF_AT,
	CZ_MAN_SF_MK
];

czTeams = [
	CZ_SQUAD,CZ_SQUAD,CZ_SQUAD,CZ_SQUAD,CZ_SQUAD,CZ_SQUAD,CZ_SQUAD,CZ_SQUAD,
	CZ_AT_TEAM,
	CZ_SF_TEAM
];

czSnipers = [[CZ_MAN_SNIPER,CZ_MAN_SPOTTER]];

CZ_VEHICLE_AMMOS = [
	"30Rnd_762x39_AK47",
	"30Rnd_556x45_G36",
	"handgrenade_west",
	"100Rnd_762x51_M240",
	"100Rnd_556x45_M249",
	"100Rnd_762x54_PK",
	"maaws_hedp",
	"maaws_heat",
	"m136",
	"javelin",
	"1Rnd_HE_M203",
	"pipebomb",
	"mine",
	"10Rnd_762x51_CZ750"
];

czCars = [
	["LandRover_ACR",CZ_MAN,CZ_SQUAD,[],CZ_VEHICLE_AMMOS],
	["Dingo_GL_Wdl_ACR",CZ_MAN_TANK_CREW,CZ_SQUAD,[],CZ_VEHICLE_AMMOS],
	["Dingo_WDL_ACR",CZ_MAN_TANK_CREW,CZ_SQUAD,[],CZ_VEHICLE_AMMOS],
	["T810_ACR",CZ_MAN,CZ_SQUAD,[],CZ_VEHICLE_AMMOS],
	["T810A_MG_ACR",CZ_MAN,CZ_SQUAD,[],CZ_VEHICLE_AMMOS],
	["T810_Open_ACR",CZ_MAN,CZ_SQUAD,[],CZ_VEHICLE_AMMOS],
	["UAZ_Unarmed_ACR",CZ_MAN,CZ_SQUAD,[],CZ_VEHICLE_AMMOS]
];

czArm = [//ACR armour added
	["BRDM2_ACR",CZ_MAN_TANK_CREW,CZ_SQUAD,[],CZ_VEHICLE_AMMOS],
	["Pandur2_ACR",CZ_MAN_TANK_CREW,CZ_SQUAD,[],CZ_VEHICLE_AMMOS],
	["BMP2_ACR",CZ_MAN_TANK_CREW,CZ_SQUAD,[],CZ_VEHICLE_AMMOS],
	["T72_ACR",CZ_MAN_TANK_CREW,CZ_SQUAD,[],[]]
];

czHelis = [
	["Mi24_D_CZ_ACR",CZ_MAN_PILOT],
	["Mi171Sh_rockets_CZ_EP1",CZ_MAN_PILOT],
	["Mi171Sh_CZ_EP1",CZ_MAN_PILOT]
];//added ACR Mi24

czAir = [
	["L159_ACR",CZ_MAN_PILOT],
	["L39_2_ACR",CZ_MAN_PILOT]
];//added ACR L39 and L159

CZ_PLAYER_PISTOLS = WPN_NO_SEC+WPN_NO_SEC+[WPN_CZ75_C,WPN_CZ75_D,WPN_CZ75_P,WPN_CZ75_P_SD];

czPLIST = [
	[west,[CZ_SOLDIERS,[WPN_CZ805A1],CZ_PLAYER_PISTOLS,WPN_GRENADE_W,CZ_AMMOS,CZ_GRENS,WPNS_NVG],"Czech Soldier CZ805 BREN A1"],
	[west,[CZ_SOLDIERS,[WPN_CZ805A1GL],WPN_NO_SEC,WPN_GRENADE_W,CZ_AMMOS,CZ_GRENS,WPNS_NVG],"Czech Soldier CZ805 BREN A1 GL"],
	[west,[CZ_SOLDIERS,[WPN_M249SCOPE],CZ_PLAYER_PISTOLS,WPN_GRENADE_W,[4,5],[1,2],WPNS_NVG],"Czech Solider M249 Scope"],
	[west,[CZ_SOLDIERS,[WPN_UK59],CZ_PLAYER_PISTOLS,WPN_GRENADE_W,[4,5],[1,2],WPNS_NVG],"Czech Machinegunner UK59"],
	[west,[CZ_SOLDIERS,[WPN_M60],CZ_PLAYER_PISTOLS,WPN_GRENADE_W,[4,5],[1,2],WPNS_NVG],"Czech Machinegunner M60"],
	[west,[CZ_SOLDIERS,[WPN_SA58CCO],[WPN_MAAWS],WPN_GRENADE_W,[4,5],[0,1],WPNS_NVG],"Czech AT Soldier MAAWS HEDP"],
	[west,[CZ_SOLDIERS,[WPN_SA58CCO],[WPN_MAAWS2],WPN_GRENADE_W,[4,5],[0,1],WPNS_NVG],"Czech AT Soldier MAAWS HEAT"],
	[west,[CZ_SOLDIERS,[WPN_SA58CCO],[WPN_JAV],WPN_GRENADE_W,[4,5],[0,1],WPNS_NVG],"Czech AT Soldier Javelin"],
	[west,[CZ_SOLDIERS,[WPN_SA58CCO],[WPN_RPGL],WPN_GRENADE_W,[4,5],[0,1],WPNS_NVG],"Czech AT Soldier RPG7"],
	[west,[CZ_SOLDIERS,[WPN_CZ805A1],[WPN_STING],WPN_GRENADE_W,[5],[0,1],WPNS_NVG],"Czech AA Soldier Stinger"],
	[west,[["CZ_Soldier_Medic_Wdl_ACR"],[WPN_CZ805A2],WPN_NO_SEC,"SmokeShell",[5],[3],WPNS_NVG],"Czech Medic"],
	[west,[["CZ_Soldier_Spec2_Wdl_ACR"],[WPN_CZ805BGL],[WPN_CZ75_P,WPN_CZ75_P_SD],WPN_GRENADE_W,[8],[2,3,4],WPNS_NVG_RF],"Czech Special Forces CZ805 BREN B1 GL"],
	[west,[["CZ_Soldier_Spec2_Wdl_ACR"],[WPN_M249SCOPE],[WPN_CZ75_P,WPN_CZ75_P_SD],WPN_GRENADE_W,[4],[2,3,4],WPNS_NVG_RF],"Czech Special Forces M249 Scope"],
	[west,[["CZ_Soldier_Spec2_Wdl_ACR"],[WPN_CZ805BGL],[WPN_M136],WPN_GRENADE_W,[5],[0,1],WPNS_NVG_RF],"Czech Special Forces M136"],
	[west,[["CZ_Soldier_Spec2_Wdl_ACR"],[WPN_CZ750],[WPN_CZ75_P,WPN_CZ75_P_SD],WPN_GRENADE_W,[9],[0,1,2,3],WPNS_NVG_RF],"Czech Special Forces CZ750"],
	[west,[["CZ_Soldier_Sniper_EP1"],[WPN_CZ750],[WPN_CZ75_P,WPN_CZ75_P_SD],"SmokeShell",[8],[2,3,4],WPNS_NVG_RF],"Czech Sniper CZ750"]
];


//---- Cherarussian Defence Forces ----

CD_AMMOS = [5,6,7,8];
CD_GRENS = [1,2,3,4];
CD_SOLDIERS = ["CDF_Soldier"];
CD_MAN = [["CDF_Soldier"],[WPN_AK74,WPN_AK74,WPN_AK74,WPN_AK74,WPN_AK74,WPN_AK74,WPN_AKS74_PSO,WPN_AK74GL],WPN_NO_SEC,WPN_GRENADE_E,CD_AMMOS,CD_GRENS,[]];
CD_MAN_MG = [["CDF_Soldier"],[WPN_PK,WPN_RPK],WPN_NO_SEC,WPN_GRENADE_E,[5],[2],[]];
CD_MAN_AT = [["CDF_Soldier"],[WPN_AK74],[WPN_RPG18,WPN_RPGL,WPN_RPGL],WPN_GRENADE_E,[5],[1],[]];
CD_MAN_AA = [["CDF_Soldier"],[WPN_AK74],[WPN_STRELA],WPN_NO_GREN,CD_AMMOS,CD_GRENS,[]];
CD_MAN_MEDIC = [["CDF_Soldier_Medic"],[WPN_AKSU74],WPN_NO_SEC,"SmokeShell",[5],[3],[]];
CD_MAN_DRIVER = [["CDF_Soldier"],[WPN_AKSU74],WPN_NO_SEC,WPN_GRENADE_E,[4,5,6],[0,1,2],WPNS_NVG];
CD_MAN_TANK_CREW = [["CDF_Soldier_Crew"],[WPN_AKSU74],WPN_NO_SEC,WPN_GRENADE_E,[4,5,6],[0,1,2],WPNS_NVG];
CD_MAN_PILOT = [["CDF_Soldier_Pilot"],[WPN_AKSU74],WPN_NO_SEC,"SmokeShell",CD_AMMOS,CD_GRENS,WPNS_NVG];
CD_MAN_SNIPER = [["CDF_Soldier_Sniper"],[WPN_SVD],[WPN_MAKAROV],"SmokeShell",[8],CD_GRENS,WPNS_NVG_BINO];
CD_MAN_SPOTTER = [["CDF_Soldier_Sniper"],[WPN_AK74,WPN_AK74GL],WPN_NO_SEC,WPN_GRENADE_E,CD_AMMOS,CD_GRENS,WPNS_NVG_BINO];
CD_MAN_MILITIA = [["CDF_Soldier_Militia"],[WPN_AKs],WPN_NO_SEC,WPN_GRENADE_E,CD_AMMOS,[0,1,2],[]];

CD_SQUAD = [6,10,
	CD_MAN,CD_MAN,CD_MAN,CD_MAN,CD_MAN,CD_MAN,CD_MAN,CD_MAN,
	CD_MAN_MG,CD_MAN_MG,
	CD_MAN_AT,CD_MAN_AT,
	CD_MAN_AA,
	CD_MAN_MEDIC
];

CD_AT_TEAM = [2,4,CD_MAN_AT];

CD_MILITIA_SQUAD = [4,8,CD_MAN_MILITIA];

cdTeams = [
	CD_SQUAD,CD_SQUAD,CD_SQUAD,CD_SQUAD,CD_SQUAD,CD_SQUAD,CD_SQUAD,
	CD_AT_TEAM,CD_SQUAD,
	CD_MILITIA_SQUAD
];

cdSnipers = [[CD_MAN_SNIPER,CD_MAN_SPOTTER]];

_CD_VEH_AMMOS = [
	"30Rnd_545x39_AK",
	"30Rnd_762x39_AK47",
	"handgrenade_east",
	"100Rnd_762x54_PK",
	"75Rnd_545x39_RPK",
	"1Rnd_HE_GP25",
	"pg7vl",
	"RPG18",
	"pipebomb",
	"10Rnd_762x54_SVD",
	"minee",
	"strela"
];

cdCars = [
	["UAZ_CDF",CD_MAN_DRIVER,CD_SQUAD,[],_CD_VEH_AMMOS],
	["UAZ_AGS30_CDF",CD_MAN_DRIVER,CD_SQUAD,[],_CD_VEH_AMMOS],
	["UAZ_MG_CDF",CD_MAN_DRIVER,CD_SQUAD,[],_CD_VEH_AMMOS],
	["Ural_CDF",CD_MAN_DRIVER,CD_SQUAD,[],_CD_VEH_AMMOS],
	["UralOpen_CDF",CD_MAN_DRIVER,CD_SQUAD,[],_CD_VEH_AMMOS]
];

cdArm = [
	["BMP2_CDF",CD_MAN_TANK_CREW,CD_SQUAD,[],_CD_VEH_AMMOS],
	["BRDM2_CDF",CD_MAN_TANK_CREW,CD_SQUAD,[],_CD_VEH_AMMOS],
	["BRDM2_ATGM_CDF",CD_MAN_TANK_CREW,CD_SQUAD,[],[]],
	["T72_CDF",CD_MAN_TANK_CREW,CD_SQUAD,[],[]],
	["ZSU_CDF",CD_MAN_TANK_CREW,CD_SQUAD,[],[]]
];

cdHelis = [["Mi24_D",CD_MAN_PILOT],["Mi17_CDF",CD_MAN_PILOT]];

cdAir = [["Su25_CDF",CD_MAN_PILOT]];

CD_PLAYER_PISTOLS = WPN_NO_SEC+WPN_NO_SEC+[WPN_MAKAROV,WPN_MAKAROV,WPN_MAKAROV,WPN_MAKAROV_SD];

cdPLIST = [
	[west,[CD_SOLDIERS,[WPN_AK74],CD_PLAYER_PISTOLS,WPN_GRENADE_E,CD_AMMOS,CD_GRENS,[]],"CDF Soldier AK74"],
	[west,[CD_SOLDIERS,[WPN_AK74GL],CD_PLAYER_PISTOLS,WPN_GRENADE_E,CD_AMMOS,CD_GRENS,[]],"CDF Soldier AK74 GP25"],
	[west,[CD_SOLDIERS,[WPN_AKSU74],CD_PLAYER_PISTOLS,WPN_GRENADE_E,CD_AMMOS,CD_GRENS,[]],"CDF Soldier AKSU74"],
	[west,[CD_SOLDIERS,[WPN_AKS74_PSO],CD_PLAYER_PISTOLS,WPN_GRENADE_E,CD_AMMOS,CD_GRENS,[]],"CDF Marksman AKS74 PSO"],
	[west,[CD_SOLDIERS,[WPN_SVD],CD_PLAYER_PISTOLS,WPN_GRENADE_E,CD_AMMOS,CD_GRENS,WPNS_BINO],"CDF Marksman SVD"],
	[west,[["CDF_Soldier_Militia"],[WPN_AKS],CD_PLAYER_PISTOLS,WPN_GRENADE_E,CD_AMMOS,[0,1,2],[]],"CDF Militia AKS"],
	[west,[CD_SOLDIERS,[WPN_PK],CD_PLAYER_PISTOLS,WPN_GRENADE_E,[4,5],[0,1,2],[]],"CDF Machinegunner PK"],
	[west,[CD_SOLDIERS,[WPN_RPK],CD_PLAYER_PISTOLS,WPN_GRENADE_E,[4,5],[0,1,2],[]],"CDF Machinegunner RPK"],
	[west,[CD_SOLDIERS,[WPN_AK74],[WPN_RPGL],WPN_GRENADE_E,[4],[0,1,2],[]],"CDF AT Soldier RPG7VL"],
	[west,[CD_SOLDIERS,[WPN_AK74],[WPN_RPG18],WPN_GRENADE_E,[4],[0,1,2],[]],"CDF AT Soldier RPG18"],
	[west,[CD_SOLDIERS,[WPN_AK74],[WPN_STRELA],WPN_GRENADE_E,CD_AMMOS,CD_GRENS,[]],"CDF AA Soldier"],
	[west,[["CDF_Soldier_Medic"],[WPN_AKSU74],WPN_NO_SEC,"SmokeShell",[3,4,5],[0,1,2],[]],"CDF Medic"],
	[west,[["CDF_Soldier_Sniper"],[WPN_SVD],[WPN_MAKAROV],"SmokeShell",[8],CD_GRENS,WPNS_NVG_BINO],"CDF Sniper SVD"]
];


//---- Nationalist guerillas of the National Party ----

NP_AMMOS = [4,5,6];
NP_GRENS = [0,1,2];
NP_RIFLES = [WPN_AKM,WPN_AKM,WPN_AKs,WPN_AKS,WPN_AK74,WPN_AK74,WPN_M16A2,WPN_M16A2,WPN_AKS74_PSO];
NP_SOLDIERS = ["GUE_Soldier_1","GUE_Soldier_2"];

NP_MAN = [NP_SOLDIERS,NP_RIFLES+[WPN_AK74GL,WPN_M16A2GL],WPN_NO_SEC,WPN_GRENADE_E,NP_AMMOS,NP_GRENS,[]];
NP_MAN_MG = [NP_SOLDIERS,[WPN_PK,WPN_RPK],WPN_NO_SEC,WPN_GRENADE_E,[5],[2],[]];
NP_MAN_AT = [NP_SOLDIERS,NP_RIFLES,[WPN_RPG,WPN_RPGO,WPN_RPGL],WPN_GRENADE_E,[5],[1],[]];
NP_MAN_AA = [NP_SOLDIERS,NP_RIFLES,[WPN_STING],WPN_NO_GREN,NP_AMMOS,NP_GRENS,[]];
NP_MAN_MEDIC = [["GUE_Soldier_Medic"],[WPN_AKSU74,WPN_AKs],WPN_NO_SEC,"SmokeShell",NP_AMMOS,NP_GRENS,[]];
NP_MAN_DRIVER = [NP_SOLDIERS,NP_RIFLES,WPN_NO_SEC,WPN_GRENADE_E,[4,5,6],[0,1,2],WPNS_NVG];
NP_MAN_SNIPER = [["GUE_Soldier_Sniper"],[WPN_SVD],[WPN_M9],"SmokeShell",[8],NP_GRENS,WPNS_NVG_BINO];
NP_MAN_SPOTTER = [["GUE_Soldier_Sniper"],[WPN_AKM,WPN_M16A2,WPN_AK74GL,WPN_M16A2GL],WPN_NO_SEC,WPN_GRENADE_E,NP_AMMOS,NP_GRENS,WPNS_NVG_BINO];

NP_SQUAD = [6,10,
	NP_MAN,NP_MAN,NP_MAN,NP_MAN,NP_MAN,NP_MAN,NP_MAN,NP_MAN,
	NP_MAN_MG,NP_MAN_MG,
	NP_MAN_AT,NP_MAN_AT,
	NP_MAN_AA,
	NP_MAN_MEDIC
];

NP_SECTION = [3,6,NP_MAN,NP_MAN,NP_MAN_AT];

NP_AT_TEAM = [2,3,NP_MAN_AT];

npTeams = [
	NP_SQUAD,NP_SQUAD,NP_SQUAD,NP_SQUAD,NP_SQUAD,NP_SQUAD,
	NP_SECTION,NP_SECTION,
	NP_AT_TEAM,NP_AT_TEAM
];

npSnipers = [[NP_MAN_SNIPER,NP_MAN_SPOTTER]];

_NP_VEH_AMMOS = [
	"30Rnd_545x39_AK",
	"30Rnd_762x39_AK47",
	"30Rnd_556x45_Stanag",
	"handgrenade_east",
	"100Rnd_762x54_PK",
	"75Rnd_545x39_RPK",
	"1Rnd_HE_GP25",
	"1Rnd_HE_M203",
	"PG7V",
	"pg7vl",
	"OG7",
	"pipebomb",
	"10Rnd_762x54_SVD",
	"minee",
	"stinger"
];

npCars = [
	["Offroad_DSHKM_Gue",NP_MAN_DRIVER,NP_SQUAD,[],_NP_VEH_AMMOS],
	["Offroad_SPG9_Gue",NP_MAN_DRIVER,NP_SQUAD,[],_NP_VEH_AMMOS],
	["Pickup_PK_GUE",NP_MAN_DRIVER,NP_SQUAD,[],_NP_VEH_AMMOS],
	["V3S_Gue",NP_MAN_DRIVER,NP_SQUAD,[],_NP_VEH_AMMOS],
	["Ural_ZU23_Gue",NP_MAN_DRIVER,NP_SQUAD,[],_NP_VEH_AMMOS]
];

npArm = [
	["BMP2_Gue",NP_MAN_DRIVER,NP_SQUAD,[],_NP_VEH_AMMOS],
	["BRDM2_Gue",NP_MAN_DRIVER,NP_SQUAD,[],_NP_VEH_AMMOS],
	["T34",NP_MAN_DRIVER,NP_SQUAD,[[1]],[]],
	["T72_Gue",NP_MAN_DRIVER,NP_SQUAD,[],[]]
];

NP_PLAYER_PISTOLS = WPN_NO_SEC+WPN_NO_SEC+[WPN_MAKAROV,WPN_MAKAROV,WPN_M9,WPN_M9SD,WPN_MAKAROV_SD];

npPLIST = [
	[west,[NP_SOLDIERS,[WPN_AKM],NP_PLAYER_PISTOLS,WPN_GRENADE_E,NP_AMMOS,NP_GRENS,[]],"NAPA Guerilla AKM"],
	[west,[NP_SOLDIERS,[WPN_AKS],NP_PLAYER_PISTOLS,WPN_GRENADE_E,NP_AMMOS,NP_GRENS,[]],"NAPA Guerilla AKS"],
	[west,[NP_SOLDIERS,[WPN_AK74],NP_PLAYER_PISTOLS,WPN_GRENADE_E,NP_AMMOS,NP_GRENS,[]],"NAPA Guerilla AK74"],
	[west,[NP_SOLDIERS,[WPN_AK74GL],WPN_NO_SEC,WPN_GRENADE_E,NP_AMMOS,NP_GRENS,[]],"NAPA Guerilla AK75 GP25"],
	[west,[NP_SOLDIERS,[WPN_M16A2],NP_PLAYER_PISTOLS,WPN_GRENADE_E,NP_AMMOS,NP_GRENS,[]],"NAPA Guerilla M16A2"],
	[west,[NP_SOLDIERS,[WPN_M16A2GL],WPN_NO_SEC,WPN_GRENADE_E,NP_AMMOS,NP_GRENS,[]],"NAPA Guerilla M16A2 M203"],
	[west,[NP_SOLDIERS,[WPN_AKS74_PSO],NP_PLAYER_PISTOLS,WPN_GRENADE_E,NP_AMMOS,NP_GRENS,[]],"NAPA Guerilla AKS74 PSO"],
	[west,[NP_SOLDIERS,[WPN_SVD],NP_PLAYER_PISTOLS,WPN_GRENADE_E,NP_AMMOS,NP_GRENS,[]],"NAPA Guerilla SVD"],
	[west,[NP_SOLDIERS,[WPN_PK],NP_PLAYER_PISTOLS,WPN_GRENADE_E,[3,4,5],[0,1,2],[]],"NAPA Guerilla PK"],
	[west,[NP_SOLDIERS,[WPN_RPK],NP_PLAYER_PISTOLS,WPN_GRENADE_E,[3,4,5],[0,1,2],[]],"NAPA Guerilla RPK"],
	[west,[NP_SOLDIERS,[WPN_AKS],[WPN_RPGL],WPN_GRENADE_E,[4,5],[0,1],[]],"NAPA Guerilla RPG7VL"],
	[west,[NP_SOLDIERS,[WPN_AKS],[WPN_RPGO],WPN_GRENADE_E,[4,5],[0,1],[]],"NAPA Guerilla RPG7 HE"],
	[west,[NP_SOLDIERS,[WPN_AKS],[WPN_STING],WPN_GRENADE_E,[4,5],[0,1],[]],"NAPA Guerilla STINGER"],
	[west,[["GUE_Soldier_Medic"],[WPN_AKs],WPN_NO_SEC,"SmokeShell",NP_AMMOS,NP_GRENS,[]],"NAPA Guerilla Medic"]
];


//---- Russian Armed Forces ----

RU_AMMOS = [6,7,8];
RU_GRENS = [2,3,4];
RU_SOLDIERS = ["RU_Soldier"];
RU_MAN = [["RU_Soldier"],[WPN_AK107,WPN_AK107,WPN_AK107,WPN_AK107,WPN_AK107_SCOPE,WPN_AK107GL,WPN_AK107GL_SCOPE],WPN_NO_SEC,WPN_GRENADE_E,RU_AMMOS,RU_GRENS,WPNS_NVG];
RU_MAN_MG = [["RU_Soldier"],[WPN_PK,WPN_PK_SCOPE],WPN_NO_SEC,WPN_GRENADE_E,[5],[2],WPNS_NVG];
RU_MAN_AT = [["RU_Soldier"],[WPN_AK107],[WPN_RPG18,WPN_RPGL,WPN_RPGR,WPN_AT13],WPN_GRENADE_E,[5],[1],WPNS_NVG];
RU_MAN_AA = [["RU_Soldier"],[WPN_AK107],[WPN_IGLA],WPN_NO_GREN,RU_AMMOS,RU_GRENS,WPNS_NVG];
RU_MAN_MEDIC = [["RU_Soldier_Medic"],[WPN_AKSU74],WPN_NO_SEC,"SmokeShell",[5],[3],WPNS_NVG];
RU_MAN_DRIVER = [["RU_Soldier"],[WPN_AKSU74],WPN_NO_SEC,WPN_GRENADE_E,[4,5,6],[0,1,2],WPNS_NVG];
RU_MAN_TANK_CREW = [["RU_Soldier_Crew"],[WPN_AKSU74],WPN_NO_SEC,WPN_GRENADE_E,[4,5,6],[0,1,2],WPNS_NVG];
RU_MAN_PILOT = [["RU_Soldier_Pilot"],[WPN_AKSU74],WPN_NO_SEC,"SmokeShell",RU_AMMOS,RU_GRENS,WPNS_NVG];
RU_MAN_SNIPER = [["RU_Soldier_Sniper"],[WPN_SVD_CAMO,WPN_SVD_CAMO,WPN_KSVK],[WPN_MAKAROV],"SmokeShell",[8],RU_GRENS,WPNS_NVG_BINO];
RU_MAN_SPOTTER = [["RU_Soldier_Sniper"],[WPN_AK107,WPN_AK107GL],WPN_NO_SEC,WPN_GRENADE_E,RU_AMMOS,RU_GRENS,WPNS_NVG_BINO];
RU_MAN_SPETZ = [["Rus_Soldier1"],[WPN_BIZON,WPN_AK107,WPN_AK107,WPN_AK107GL,WPN_AK107_SCOPE,WPN_AK107GL_SCOPE,WPN_SVD],[WPN_MAKAROV],WPN_GRENADE_E,[8],[4],WPNS_NVG_BINO];
RU_MAN_SPETZ_AT = [["Rus_Soldier1"],[WPN_AK107,WPN_AK107,WPN_AK107_SCOPE],[WPN_RPG18,WPN_RPGL,WPN_RPGR],WPN_GRENADE_E,[8],[4],WPNS_NVG_BINO];
RU_MAN_SPETZ_MG = [["Rus_Soldier1"],[WPN_PK,WPN_PK_SCOPE],[WPN_MAKAROV],WPN_GRENADE_E,[5],[2],WPNS_NVG_BINO];
RU_MAN_SPETZ_SD = [["Rus_Soldier1"],[WPN_AKS74KOBRA_SD,WPN_AKS74KOBRA_SD,WPN_BIZON_SD,WPN_VSS],[WPN_MAKAROV_SD],WPN_GRENADE_E,[8],[4],WPNS_NVG_BINO];

RU_SQUAD = [6,10,
	RU_MAN,RU_MAN,RU_MAN,RU_MAN,RU_MAN,RU_MAN,RU_MAN,RU_MAN,
	RU_MAN_MG,RU_MAN_MG,
	RU_MAN_AT,RU_MAN_AT,
	RU_MAN_AA,
	RU_MAN_MEDIC
];

RU_AT_TEAM = [3,5,RU_MAN_AT];

RU_SPETZ_TEAM = [4,8,
	RU_MAN_SPETZ,RU_MAN_SPETZ,
	RU_MAN_SPETZ_AT,
	RU_MAN_SPETZ_MG
];

RU_SPETZ_TEAM_SD = [4,8,RU_MAN_SPETZ_SD];

ruTeams = [
	RU_SQUAD,RU_SQUAD,RU_SQUAD,RU_SQUAD,RU_SQUAD,RU_SQUAD,
	RU_AT_TEAM,RU_AT_TEAM,
	RU_SPETZ_TEAM,
	RU_SPETZ_TEAM_SD
];

ruSnipers = [[RU_MAN_SNIPER,RU_MAN_SPOTTER]];

_RU_VEH_AMMOS = [
	"30Rnd_545x39_AK",
	"30Rnd_762x39_AK47",
	"handgrenade_east",
	"100Rnd_762x54_PK",
	"75Rnd_545x39_RPK",
	"1Rnd_HE_GP25",
	"PG7V",
	"pg7vl",
	"OG7",
	"RPG18",
	"pipebomb",
	"10Rnd_762x54_SVD",
	"5Rnd_127x108_KSVK",
	"minee",
	"AT13",
	"Igla"
];

ruCars = [
	["UAZ_RU",RU_MAN_DRIVER,RU_SQUAD,[],_RU_VEH_AMMOS],
	["UAZ_AGS30_RU",RU_MAN_DRIVER,RU_SQUAD,[],_RU_VEH_AMMOS],
	["Kamaz",RU_MAN_DRIVER,RU_SQUAD,[],_RU_VEH_AMMOS],
	["KamazOpen",RU_MAN_DRIVER,RU_SQUAD,[],_RU_VEH_AMMOS],
	["GAZ_Vodnik",RU_MAN_DRIVER,RU_SQUAD,[],_RU_VEH_AMMOS],
	["GAZ_Vodnik_HMG",RU_MAN_TANK_CREW,RU_SQUAD,[],_RU_VEH_AMMOS]
];

ruArm = [
	["2S6M_Tunguska",RU_MAN_TANK_CREW,RU_SQUAD,[],[]],
	["BMP3",RU_MAN_TANK_CREW,RU_SQUAD,[[1],[2]],_RU_VEH_AMMOS],
	["BTR90",RU_MAN_TANK_CREW,RU_SQUAD,[],_RU_VEH_AMMOS],
	["T72_RU",RU_MAN_TANK_CREW,RU_SQUAD,[],[]],
	["T90",RU_MAN_TANK_CREW,RU_SQUAD,[],[]]
];

ruHelis = [["Ka52",RU_MAN_PILOT],["Ka52black",RU_MAN_PILOT],["Mi24_V",RU_MAN_PILOT],["Mi24_p",RU_MAN_PILOT],["Mi17_rockets_RU",RU_MAN_PILOT]];

ruAir = [["Su39",RU_MAN_PILOT],["Su34",RU_MAN_PILOT]];

RU_PLAYER_PISTOLS = WPN_NO_SEC+WPN_NO_SEC+[WPN_MAKAROV,WPN_MAKAROV,WPN_MAKAROV,WPN_MAKAROV_SD];

ruPLIST = [
	[east,[RU_SOLDIERS,[WPN_AK107],RU_PLAYER_PISTOLS,WPN_GRENADE_E,RU_AMMOS,RU_GRENS,WPNS_NVG],"Russian Soldier AK107"],
	[east,[RU_SOLDIERS,[WPN_AK107_SCOPE],RU_PLAYER_PISTOLS,WPN_GRENADE_E,RU_AMMOS,RU_GRENS,WPNS_NVG],"Russian Soldier AK107 PSO"],
	[east,[RU_SOLDIERS,[WPN_AK107GL],WPN_NO_SEC,WPN_GRENADE_E,RU_AMMOS,RU_GRENS,WPNS_NVG],"Russian Soldier AK107 GP25"],
	[east,[RU_SOLDIERS,[WPN_AK107GL_SCOPE],WPN_NO_SEC,WPN_GRENADE_E,RU_AMMOS,RU_GRENS,WPNS_NVG],"Russian Soldier AK107 PSO GP25"],
	[east,[RU_SOLDIERS,[WPN_PK],RU_PLAYER_PISTOLS,WPN_GRENADE_E,[5],[2],WPNS_NVG],"Russian Machinegunner PK"],
	[east,[RU_SOLDIERS,[WPN_PK_SCOPE],RU_PLAYER_PISTOLS,WPN_GRENADE_E,[5],[2],WPNS_NVG],"Russian Machinegunner PK Scope"],
	[east,[RU_SOLDIERS,[WPN_RPK],RU_PLAYER_PISTOLS,WPN_GRENADE_E,[5],[2],WPNS_NVG],"Russian Machinegunner RPK"],
	[east,[RU_SOLDIERS,[WPN_AK107],[WPN_RPGL],WPN_GRENADE_E,[5],[1],WPNS_NVG],"Russian AT Soldier RPG7VL"],
	[east,[RU_SOLDIERS,[WPN_AK107],[WPN_RPGR],WPN_GRENADE_E,[5],[1],WPNS_NVG],"Russian AT Soldier RPG7VR"],
	[east,[RU_SOLDIERS,[WPN_AK107],[WPN_RPG18],WPN_GRENADE_E,[5],[1],WPNS_NVG],"Russian AT Soldier RPG18"],
	[east,[RU_SOLDIERS,[WPN_AK107],[WPN_AT13],WPN_GRENADE_E,[5],[1],WPNS_NVG],"Russian AT Soldier AT13"],
	[east,[RU_SOLDIERS,[WPN_AK107],[WPN_IGLA],WPN_GRENADE_E,[5],[1],WPNS_NVG],"Russian AA Soldier"],
	[east,[["RU_Soldier_Medic"],[WPN_AKSU74],WPN_NO_SEC,"SmokeShell",[5],[3],WPNS_NVG],"Russian Medic"],
	[east,[["Rus_Soldier1"],[WPN_AK107],[WPN_MAKAROV],WPN_GRENADE_E,[8],[4],WPNS_NVG_BINO],"Russian Spetsnaz AK107"],
	[east,[["Rus_Soldier1"],[WPN_AK107_SCOPE],[WPN_MAKAROV],WPN_GRENADE_E,[8],[4],WPNS_NVG_BINO],"Russian Spetsnaz AK107 PSO"],
	[east,[["Rus_Soldier1"],[WPN_AK107GL],WPN_NO_SEC,WPN_GRENADE_E,[8],[4],WPNS_NVG_BINO],"Russian Spetsnaz AK107 GP25"],
	[east,[["Rus_Soldier1"],[WPN_AK107GL_SCOPE],WPN_NO_SEC,WPN_GRENADE_E,[8],[4],WPNS_NVG_BINO],"Russian Spetsnaz AK107 PSO GP25"],
	[east,[["Rus_Soldier1"],[WPN_SVD],[WPN_MAKAROV],WPN_GRENADE_E,[8],[4],WPNS_NVG_BINO],"Russian Spetsnaz SVD"],
	[east,[["Rus_Soldier1"],[WPN_VSS],[WPN_MAKAROV_SD],WPN_GRENADE_E,[8],[4],WPNS_NVG_BINO],"Russian Spetsnaz VSS"],
	[east,[["Rus_Soldier1"],[WPN_BIZON],[WPN_MAKAROV],WPN_GRENADE_E,[8],[4],WPNS_NVG_BINO],"Russian Spetsnaz Bizon"],
	[east,[["Rus_Soldier1"],[WPN_BIZON_SD],[WPN_MAKAROV_SD],WPN_GRENADE_E,[8],[4],WPNS_NVG_BINO],"Russian Spetsnaz Bizon SD"],
	[east,[["Rus_Soldier1"],[WPN_AKS74KOBRA_SD],[WPN_MAKAROV_SD],WPN_GRENADE_E,[8],[4],WPNS_NVG_BINO],"Russian Spetsnaz AKSU74 SD"],
	[east,[["Rus_Soldier1"],[WPN_PK],[WPN_MAKAROV],WPN_GRENADE_E,[5],[2],WPNS_NVG_BINO],"Russian Spetsnaz PK"],
	[east,[["Rus_Soldier1"],[WPN_PK_SCOPE],[WPN_MAKAROV],WPN_GRENADE_E,[5],[2],WPNS_NVG_BINO],"Russian Spetsnaz PK Scope"],
	[east,[["Rus_Soldier1"],[WPN_RPK],[WPN_MAKAROV],WPN_GRENADE_E,[5],[2],WPNS_NVG_BINO],"Russian Spetsnaz RPK"],
	[east,[["Rus_Soldier1"],[WPN_AK107],[WPN_RPGL],WPN_GRENADE_E,[5],[1],WPNS_NVG_BINO],"Russian Spetsnaz RPG7VL"],
	[east,[["Rus_Soldier1"],[WPN_AK107],[WPN_RPG18],WPN_GRENADE_E,[5],[1],WPNS_NVG_BINO],"Russian Spetsnaz RPG18"],
	[east,[["RU_Soldier_Sniper"],[WPN_SVD_CAMO],[WPN_MAKAROV],"SmokeShell",[8],RU_GRENS,WPNS_NVG_BINO],"Russian Sniper SVD"],
	[east,[["RU_Soldier_Sniper"],[WPN_KSVK],[WPN_MAKAROV],"SmokeShell",[8],RU_GRENS,WPNS_NVG_BINO],"Russian Sniper KVSK"]
];


//---- Chernarussian Movement of the Red Star ----

CH_AMMOS = [4,5,6,7];
CH_GRENS = [0,1,2,3];
CH_RIFLES = [WPN_AKM,WPN_AKM,WPN_AKs,WPN_AKS,WPN_AK74,WPN_AK74,WPN_AKSU74,WPN_AKS74_PSO];
CH_SOLDIERS = ["INS_Soldier_1","INS_Soldier_2"];

CH_MAN = [CH_SOLDIERS,CH_RIFLES+[WPN_AK74GL],WPN_NO_SEC,WPN_GRENADE_E,CH_AMMOS,CH_GRENS,[]];
CH_MAN_MG = [CH_SOLDIERS,[WPN_PK,WPN_RPK],WPN_NO_SEC,WPN_GRENADE_E,[5],[2],[]];
CH_MAN_AT = [CH_SOLDIERS,CH_RIFLES,[WPN_RPG,WPN_RPGO,WPN_RPGL,WPN_RPG18],WPN_GRENADE_E,[5],[1],[]];
CH_MAN_AA = [CH_SOLDIERS,CH_RIFLES,[WPN_STRELA],WPN_NO_GREN,CH_AMMOS,CH_GRENS,[]];
CH_MAN_MEDIC = [["INS_Soldier_Medic"],[WPN_AKSU74,WPN_AKs],WPN_NO_SEC,"SmokeShell",CH_AMMOS,CH_GRENS,[]];
CH_MAN_DRIVER = [CH_SOLDIERS,[WPN_AKSU74,WPN_AKs],WPN_NO_SEC,WPN_GRENADE_E,[4,5,6],[0,1,2],WPNS_NVG];
CH_MAN_TANK_CREW = [["INS_Soldier_Crew"],[WPN_AKSU74,WPN_AKs],WPN_NO_SEC,WPN_GRENADE_E,[4,5,6],[0,1,2],WPNS_NVG];
CH_MAN_PILOT = [["INS_Soldier_Pilot"],[WPN_AKSU74],WPN_NO_SEC,"SmokeShell",[3,4],[1,2],WPNS_NVG];
CH_MAN_SNIPER = [CH_SOLDIERS,[WPN_SVD],[WPN_MAKAROV],"SmokeShell",[8],CH_GRENS,WPNS_NVG_BINO];
CH_MAN_SPOTTER = [CH_SOLDIERS,[WPN_AKM,WPN_AK74GL],WPN_NO_SEC,WPN_GRENADE_E,CH_AMMOS,CH_GRENS,WPNS_NVG_BINO];

CH_SQUAD = [6,10,
	CH_MAN,CH_MAN,CH_MAN,CH_MAN,CH_MAN,CH_MAN,CH_MAN,CH_MAN,
	CH_MAN_MG,CH_MAN_MG,
	CH_MAN_AT,CH_MAN_AT,
	CH_MAN_AA,
	CH_MAN_MEDIC
];

CH_SECTION = [3,6,CH_MAN,CH_MAN,CH_MAN_AT];

CH_AT_TEAM = [2,3,CH_MAN_AT];

chTeams = [
	CH_SQUAD,CH_SQUAD,CH_SQUAD,CH_SQUAD,CH_SQUAD,CH_SQUAD,
	CH_SECTION,CH_SECTION,
	CH_AT_TEAM,CH_AT_TEAM
];

chSnipers = [[CH_MAN_SNIPER,CH_MAN_SPOTTER]];

_CH_VEH_AMMOS = [
	"30Rnd_545x39_AK",
	"30Rnd_762x39_AK47",
	"handgrenade_east",
	"100Rnd_762x54_PK",
	"75Rnd_545x39_RPK",
	"1Rnd_HE_GP25",
	"PG7V",
	"pg7vl",
	"OG7",
	"RPG18",
	"pipebomb",
	"10Rnd_762x54_SVD",
	"minee",
	"strela"
];

chCars = [
	["Pickup_PK_INS",CH_MAN_DRIVER,CH_SQUAD,[],_CH_VEH_AMMOS],
	["Offroad_DSHKM_INS",CH_MAN_DRIVER,CH_SQUAD,[],_CH_VEH_AMMOS],
	["UAZ_INS",CH_MAN_DRIVER,CH_SQUAD,[],_CH_VEH_AMMOS],
	["UAZ_AGS30_INS",CH_MAN_DRIVER,CH_SQUAD,[],_CH_VEH_AMMOS],
	["UAZ_SPG9_INS",CH_MAN_DRIVER,CH_SQUAD,[],_CH_VEH_AMMOS],
	["Ural_INS",CH_MAN_DRIVER,CH_SQUAD,[],_CH_VEH_AMMOS],
	["UralOpen_INS",CH_MAN_DRIVER,CH_SQUAD,[],_CH_VEH_AMMOS],
	["Ural_ZU23_INS",CH_MAN_DRIVER,CH_SQUAD,[],_CH_VEH_AMMOS]
];

chArm = [
	["BMP2_INS",CH_MAN_TANK_CREW,CH_SQUAD,[],_CH_VEH_AMMOS],
	["BRDM2_INS",CH_MAN_TANK_CREW,CH_SQUAD,[],_CH_VEH_AMMOS],
	["BRDM2_ATGM_INS",CH_MAN_TANK_CREW,CH_SQUAD,[],[]],
	["T72_INS",CH_MAN_TANK_CREW,CH_SQUAD,[],[]],
	["ZSU_INS",CH_MAN_TANK_CREW,CH_SQUAD,[],[]]
];

chHelis = [["Mi17_Ins",CH_MAN_PILOT]];

chAir = [["Su25_INS",CH_MAN_PILOT]];

CH_PLAYER_PISTOLS = WPN_NO_SEC+WPN_NO_SEC+[WPN_MAKAROV,WPN_MAKAROV,WPN_MAKAROV,WPN_MAKAROV_SD];

chPLIST = [
	[east,[CH_SOLDIERS,[WPN_AK74],CH_PLAYER_PISTOLS,WPN_GRENADE_E,CH_AMMOS,CH_GRENS,[]],"ChDKZ Insurgent AK74"],
	[east,[CH_SOLDIERS,[WPN_AKM],CH_PLAYER_PISTOLS,WPN_GRENADE_E,CH_AMMOS,CH_GRENS,[]],"ChDKZ Insurgent AKM"],
	[east,[CH_SOLDIERS,[WPN_AKS],CH_PLAYER_PISTOLS,WPN_GRENADE_E,CH_AMMOS,CH_GRENS,[]],"ChDKZ Insurgent AKS"],
	[east,[CH_SOLDIERS,[WPN_AKSU74],CH_PLAYER_PISTOLS,WPN_GRENADE_E,CH_AMMOS,CH_GRENS,[]],"ChDKZ Insurgent AKSU74"],
	[east,[CH_SOLDIERS,[WPN_AK74GL],WPN_NO_SEC,WPN_GRENADE_E,CH_AMMOS,CH_GRENS,[]],"ChDKZ Insurgent AK74 GP25"],
	[east,[CH_SOLDIERS,[WPN_AKS74_PSO],CH_PLAYER_PISTOLS,WPN_GRENADE_E,CH_AMMOS,CH_GRENS,[]],"ChDKZ Insurgent AKS74 PSO"],
	[east,[CH_SOLDIERS,[WPN_SVD],CH_PLAYER_PISTOLS,WPN_GRENADE_E,CH_AMMOS,CH_GRENS,WPNS_BINO],"ChDKZ Insurgent SVD"],
	[east,[CH_SOLDIERS,[WPN_PK],CH_PLAYER_PISTOLS,WPN_GRENADE_E,[3,4,5],[0,1,2],[]],"ChDKZ Insurgent PK"],
	[east,[CH_SOLDIERS,[WPN_RPK],CH_PLAYER_PISTOLS,WPN_GRENADE_E,[3,4,5],[0,1,2],[]],"ChDKZ Insurgent RPK"],
	[east,[CH_SOLDIERS,[WPN_AK74],[WPN_RPGL],WPN_GRENADE_E,[3,4,5],[0,1],[]],"ChDKZ Insurgent RPG7VL"],
	[east,[CH_SOLDIERS,[WPN_AK74],[WPN_RPGO],WPN_GRENADE_E,[3,4,5],[0,1],[]],"ChDKZ Insurgent RPG7 HE"],
	[east,[CH_SOLDIERS,[WPN_AK74],[WPN_RPG18],WPN_GRENADE_E,[3,4,5],[0,1],[]],"ChDKZ Insurgent RPG18"],
	[east,[CH_SOLDIERS,[WPN_AK74],[WPN_STRELA],WPN_GRENADE_E,[3,4,5],[0,1],[]],"ChDKZ Insurgent Strela"],
	[east,[["INS_Soldier_Medic"],[WPN_AKSU74],WPN_NO_SEC,"SmokeShell",CH_AMMOS,CH_GRENS,[]],"ChDKZ Medic"]
];


//---- Factions setup ----
// each faction must have 9 elements in this format:
// [side,nameString,infantry,snipers,cars,armor,helis,aircraft,players];
// the order you add them = their order on the setup screen
// the variable names (e.g. "USMC_FACTION") are used in Presets (e.g. "Insurgency") to set specific factions
USMC_FACTION = [west,"USMC",usTeams,usSnipers,usCars,usArm,usHelis,usAir,usPLIST] call addFaction;
BRIT_FACTIONS = [west,"British Army",baTeams,baSnipers,baCars,baArm,baHelis,usAir,baPLIST] call addFaction;//BAF have US air suport
CZECH_FACTION = [west,"Czech Army",czTeams,czSnipers,czCars,czArm,czHelis,czAir,czPLIST] call addFaction;
CDF_FACTION = [west,"CDF",cdTeams,cdSnipers,cdCars,cdArm,cdHelis,cdAir,cdPLIST] call addFaction;
NAPA_FACTION = [west,"NAPA",npTeams,npSnipers,npCars,npArm,[],[],npPLIST] call addFaction;//NAPA have no air units
RUSSIA_FACTION = [east,"Russian Army",ruTeams,ruSnipers,ruCars,ruArm,ruHelis,ruAir,ruPLIST] call addFaction;
CHDKZ_FACTION = [east,"ChDKZ",chTeams,chSnipers,chCars,chArm,chHelis,chAir,chPLIST] call addFaction;