WPN_NO_SEC = [["","",0,0]];
WPN_NO_GREN = "";
WPN_GRENADE_W = "HandGrenade_West";
WPN_GRENADE_E = "HandGrenade_East";

WPN_M9 = ["m9","15Rnd_9x19_M9",1,8];
WPN_M9SD = ["m9SD","15Rnd_9x19_M9SD",1,8];
WPN_G17 = ["glock17_EP1","17Rnd_9x19_glock17",1,8];
WPN_PDW = ["UZI_EP1","30Rnd_9x19_UZI",1,8];
WPN_MAKAROV = ["makarov","8Rnd_9x18_Makarov",1,8];
WPN_MAKAROV_SD = ["makarovSD","8Rnd_9x18_MakarovSD",1,8];
WPN_SKORPION = ["Sa61_EP1","20Rnd_B_765x17_Ball",1,8];
WPN_M1911 = ["Colt1911","7Rnd_45ACP_1911",1,8];

WPN_M16A4 = ["m16a4","30Rnd_556x45_Stanag"];
WPN_M4AIM = ["M4A1_Aim","30Rnd_556x45_Stanag"];
WPN_M4A1 = ["M4A1","30Rnd_556x45_Stanag"];
WPN_M249 = ["M249","200Rnd_556x45_M249"];
WPN_M249B = ["M249_EP1","100Rnd_556x45_M249"];
WPN_M249SCOPE = ["M249_m145_EP1","100Rnd_556x45_M249"];
WPN_M249TIS = ["M249_TWS_EP1","100Rnd_556x45_M249"];
WPN_M240 = ["M240","100Rnd_762x51_M240"];
WPN_M240SCOPE = ["m240_scoped_EP1","100Rnd_762x51_M240"];
WPN_M14 = ["M14_EP1","20Rnd_762x51_DMR"];
WPN_M4CCO = ["M4A3_CCO_EP1","30Rnd_556x45_Stanag"];
WPN_M16A2 = ["M16A2","30Rnd_556x45_Stanag"];
WPN_SA80SUSAT = ["BAF_L85A2_RIS_SUSAT","30Rnd_556x45_Stanag"];
WPN_SA80ACOG = ["BAF_L85A2_RIS_ACOG","30Rnd_556x45_Stanag"];
WPN_SA80AWS = ["BAF_L85A2_RIS_CWS","30Rnd_556x45_Stanag"];
WPN_LSW = ["BAF_L86A2_ACOG","30Rnd_556x45_Stanag"];
WPN_L110 = ["BAF_L110A1_Aim","200Rnd_556x45_L110A1"];
WPN_GPMG = ["BAF_L7A2_GPMG","100Rnd_762x51_M240"];
WPN_AKM = ["AK_47_M","30Rnd_762x39_AK47"];
WPN_AKS = ["AK_47_S","30Rnd_762x39_AK47"];
WPN_FAL = ["FN_FAL","20Rnd_762x51_FNFAL"];
WPN_LEE = ["LeeEnfield","10x_303"];
WPN_PK = ["PK","100Rnd_762x54_PK"];
WPN_RPK = ["RPK_74","75Rnd_545x39_RPK"];
WPN_SVD = ["SVD","10Rnd_762x54_SVD"];
WPN_AK74 = ["AK_74","30Rnd_545x39_AK"];
WPN_AKS74 = ["AKS_74","30Rnd_545x39_AK"];
WPN_AKSU74 = ["AKS_74_U","30Rnd_545x39_AK"];
WPN_AKS74PSO = ["AKS_74_pso","30Rnd_545x39_AK"];
WPN_AKS74KOBRA = ["AKS_74_kobra","30Rnd_545x39_AK"];
WPN_M24DES = ["M24_des_EP1","5Rnd_762x51_M24"];
WPN_M107 = ["m107","10Rnd_127x99_m107"];
WPN_M107TIS = ["m107_TWS_EP1","10Rnd_127x99_m107"];
WPN_M110NV = ["M110_NVG_EP1","20Rnd_762x51_B_SCAR"];
WPN_M110TIS = ["M110_TWS_EP1","20Rnd_762x51_B_SCAR"];
WPN_SVD_CAMO_DES = ["SVD_des_EP1","10Rnd_762x54_SVD"];
WPN_SVD_NPSU = ["SVD_NSPU_EP1","10Rnd_762x54_SVD"];
WPN_AKS74_NSPU = ["AKS_74_NSPU","30Rnd_545x39_AK"];
WPN_AKS74_TIS = ["AKS_74_GOSHAWK","30Rnd_545x39_AK"];
WPN_LRR_DES = ["BAF_LRR_scoped","5Rnd_86x70_L115A1"];
WPN_AS50 = ["BAF_AS50_scoped","5Rnd_127x99_as50"];
WPN_AS50TIS = ["BAF_AS50_TWS","5Rnd_127x99_as50"];
WPN_M17 = ["SCAR_H_CQC_CCO","20Rnd_762x51_B_SCAR"];
WPN_M17GL = ["SCAR_H_STD_EGLM_Spect","20Rnd_762x51_B_SCAR","1Rnd_HE_M203"];
WPN_M17SNIPER = ["SCAR_H_LNG_Sniper","20Rnd_762x51_B_SCAR"];
WPN_M17SD = ["SCAR_H_CQC_CCO_SD","20Rnd_762x51_SB_SCAR"];
WPN_M17TISSD = ["SCAR_H_STD_TWS_SD","20Rnd_762x51_SB_SCAR"];
WPN_M17SNIPERSD = ["SCAR_H_LNG_Sniper_SD","20Rnd_762x51_SB_SCAR"];
WPN_G36A_CAMO = ["G36A_camo","30Rnd_556x45_G36"];
WPN_MG36_CAMO = ["MG36_camo","100Rnd_556x45_BetaCMag"];


WPN_AK74GL = ["AK_74_GL","30Rnd_545x39_AK","1Rnd_HE_GP25"];
WPN_SA80UGL = ["BAF_L85A2_UGL_SUSAT","30Rnd_556x45_Stanag","1Rnd_HE_M203"];
WPN_M16A2GL = ["M16A2GL","30Rnd_556x45_Stanag","1Rnd_HE_M203"];
WPN_M16A4GL = ["M16A4_GL","30Rnd_556x45_Stanag","1Rnd_HE_M203"];

WPN_M136 = ["M136","M136",6,1];
WPN_MAAWS = ["MAAWS","MAAWS_HEDP",3,2];
WPN_MAAWS2 = ["MAAWS","MAAWS_HEAT",3,2];
WPN_JAV = ["Javelin","Javelin",6,1];
WPN_NLAW = ["BAF_NLAW_Launcher","NLAW",3,2];
WPN_RPG = ["RPG7V","PG7V",2,3];
WPN_RPGL = ["RPG7V","PG7VL",2,3];
WPN_RPGR = ["RPG7V","PG7VR",3,2];
WPN_RPGO = ["RPG7V","OG7",2,3];
WPN_DRAGON = ["M47Launcher_EP1","Dragon_EP1",6,1];
WPN_STING = ["Stinger","Stinger",6,1];
WPN_STRELA = ["Strela","Strela",6,1];
WPN_AT13 = ["MetisLauncher","AT13",6,1];

//----czech weapons----
WPN_SA58CCO = ["Sa58V_CCO_EP1","30Rnd_762x39_SA58"];
WPN_SA58ACOG = ["Sa58V_RCO_EP1","30Rnd_762x39_SA58"];
WPN_SA58V = ["Sa58V_EP1","30Rnd_762x39_SA58"];
WPN_M4AIM_SD = ["M4A1_AIM_SD_camo","30Rnd_556x45_StanagSD"];
WPN_M60 = ["M60A4_EP1","100Rnd_762x51_M240"];
//acr addon weapons
WPN_CZ805A1 = ["CZ805_A1_ACR","30Rnd_556x45_G36"];
WPN_CZ805A1GL = ["CZ805_A1_GL_ACR","30Rnd_556x45_G36","1Rnd_HE_M203"];
WPN_CZ805A2 = ["CZ805_A2_ACR","30Rnd_556x45_G36"];
WPN_UK59 = ["UK59_ACR","100Rnd_762x54_PK"];
WPN_CZ750 = ["CZ_750_S1_ACR","10Rnd_762x51_CZ750"];
WPN_CZ75_C = ["CZ_75_D_COMPACT","10Rnd_9x19_Compact",1,8];
WPN_CZ75_D = ["CZ_75_P_07_DUTY","15Rnd_9x19_M9",1,8];
WPN_CZ75_P = ["CZ_75_SP_01_PHANTOM","18Rnd_9x19_Phantom",1,8];
WPN_CZ75_P_SD = ["CZ_75_SP_01_PHANTOM_SD","18Rnd_9x19_PhantomSD",1,8];

//gear options
WPNS_BINO = ["Binocular"];
WPNS_NVG = ["NVGoggles"];
WPNS_NVG_RF = ["NVGoggles","Binocular_Vector"];
WPNS_NVG_BINO = ["NVGoggles","Binocular"];

SMOKE_TYPES = [
	"smokeshell","smokeshell","smokeshell","smokeshell","smokeshell","smokeshell",
	"smokeShellRed","smokeShellGreen","smokeShellBlue","SmokeShellYellow","SmokeShellPurple","SmokeShellOrange"
];

//---- United States Army----
UA_AMMOS = [6,7,8];
UA_GRENS = [2,3,4];
UA_RIFLES = [WPN_M16A4,WPN_M16A4,WPN_M16A4];
UA_MGS = [WPN_M249,WPN_M249B,WPN_M249SCOPE,WPN_M240,WPN_M240SCOPE,WPN_M249TIS];
UA_ATS = [WPN_M136,WPN_MAAWS,WPN_MAAWS2,WPN_JAV];
UA_SNIPERRIFLES = [WPN_M24DES,WPN_M107,WPN_M107TIS,WPN_M110NV,WPN_M110TIS];
UA_DELTA_GUNS = [WPN_M17,WPN_M17,WPN_M17,WPN_M17GL,WPN_M17GL,WPN_M17SNIPER];
UA_DELTA_GUNS_SD = [WPN_M17SD,WPN_M17TISSD,WPN_M17SNIPERSD];

UA_SOLDIERS = ["US_Soldier_EP1"];

UA_MAN = [UA_SOLDIERS,UA_RIFLES+[WPN_M16A4GL],WPN_NO_SEC,WPN_GRENADE_W,UA_AMMOS,UA_GRENS,WPNS_NVG];
UA_MAN_MG = [UA_SOLDIERS,UA_MGS,WPN_NO_SEC,WPN_GRENADE_W,[5],[2],WPNS_NVG];
UA_MAN_AT = [UA_SOLDIERS,UA_RIFLES,UA_ATS,WPN_GRENADE_W,[5],[1],WPNS_NVG];
UA_MAN_AA = [UA_SOLDIERS,UA_RIFLES,[WPN_STING],WPN_NO_GREN,UA_AMMOS,UA_GRENS,WPNS_NVG];
UA_MAN_MEDIC = [["US_Soldier_Medic_EP1"],[WPN_M4AIM],WPN_NO_SEC,"SmokeShell",[5],[3],WPNS_NVG];
UA_MAN_DRIVER = [["US_Soldier_EP1"],[WPN_M4A1],WPN_NO_SEC,"SmokeShell",UA_AMMOS,UA_GRENS,WPNS_NVG];
UA_MAN_TANK_CREW = [["US_Soldier_Crew_EP1"],[WPN_M4A1],WPN_NO_SEC,"SmokeShell",UA_AMMOS,UA_GRENS,WPNS_NVG];
UA_MAN_PILOT = [["US_Soldier_Pilot_EP1"],[WPN_M4A1],WPN_NO_SEC,"SmokeShell",UA_AMMOS,UA_GRENS,WPNS_NVG];
UA_MAN_SNIPER = [["US_Soldier_Sniper_EP1"],UA_SNIPERRIFLES,[WPN_M9,WPN_PDW],"SmokeShell",[8],UA_GRENS,WPNS_NVG_RF];
UA_MAN_SPOTTER = [["US_Soldier_Sniper_EP1"],[WPN_M16A4,WPN_M16A4GL],WPN_NO_SEC,"SmokeShell",UA_AMMOS,UA_GRENS,WPNS_NVG_RF];
UA_MAN_DELTA = [["US_Delta_Force_EP1"],UA_DELTA_GUNS,[WPN_M9],WPN_GRENADE_W,[8],[2,3,4],WPNS_NVG_RF];
UA_MAN_DELTA_SD = [["US_Delta_Force_EP1"],UA_DELTA_GUNS_SD,[WPN_M9SD],WPN_GRENADE_W,[8],[2,3,4],WPNS_NVG_RF];

UA_SQUAD = [6,10,
	UA_MAN,UA_MAN,UA_MAN,UA_MAN,UA_MAN,UA_MAN,UA_MAN,
	UA_MAN_MG,UA_MAN_MG,
	UA_MAN_AT,
	UA_MAN_AA,
	UA_MAN_MEDIC
];
UA_AT_TEAM = [3,5,UA_MAN_AT];
UA_DELTA_TEAM = [4,8,UA_MAN_DELTA];
UA_DELTA_TEAM_SD = [4,8,UA_MAN_DELTA_SD];

uaTeams = [
	UA_SQUAD,UA_SQUAD,UA_SQUAD,UA_SQUAD,UA_SQUAD,UA_SQUAD,UA_SQUAD,UA_SQUAD,UA_SQUAD,UA_SQUAD,//added 5 more regular squads
	UA_AT_TEAM,UA_AT_TEAM,// and added 1 more at team
	UA_DELTA_TEAM,// so delta will now be less frequent
	UA_DELTA_TEAM_SD
];

uaSnipers = [[UA_MAN_SNIPER,UA_MAN_SPOTTER]];

UA_VEHICLE_AMMOS = [
	"30Rnd_556x45_Stanag",
	"handgrenade_west",
	"20Rnd_762x51_B_SCAR",
	"100Rnd_556x45_M249",
	"100Rnd_762x51_M240",
	"1Rnd_HE_M203",
	"maaws_hedp",
	"maaws_heat",
	"m136",
	"javelin",
	"stinger",
	"pipebomb",
	"mine",
	"10Rnd_127x99_m107",
	"5Rnd_762x51_M24"
];

uaCars = [
	["HMMWV_MK19_DES_EP1",UA_MAN_DRIVER,UA_SQUAD,[],UA_VEHICLE_AMMOS],
	["HMMWV_M1151_M2_DES_EP1",UA_MAN_DRIVER,UA_SQUAD,[],UA_VEHICLE_AMMOS],
	["HMMWV_TOW_DES_EP1",UA_MAN_DRIVER,UA_AT_TEAM,[],UA_VEHICLE_AMMOS],
	["HMMWV_DES_EP1",UA_MAN_DRIVER,UA_SQUAD,[],UA_VEHICLE_AMMOS],
	["HMMWV_M998_crows_MK19_DES_EP1",UA_MAN_DRIVER,UA_SQUAD,[],UA_VEHICLE_AMMOS],
	["HMMWV_M998_crows_M2_DES_EP1",UA_MAN_DRIVER,UA_SQUAD,[],UA_VEHICLE_AMMOS],
	["MTVR_DES_EP1",UA_MAN_DRIVER,UA_SQUAD,[],UA_VEHICLE_AMMOS]
];

uaArm = [
	["M1A1_US_DES_EP1",UA_MAN_TANK_CREW,UA_SQUAD,[],[]],
	["M1A2_US_TUSK_MG_EP1",UA_MAN_TANK_CREW,UA_SQUAD,[[0,1]],[]],
	["M2A2_EP1",UA_MAN_TANK_CREW,UA_SQUAD,[],UA_VEHICLE_AMMOS],
	["M2A3_EP1",UA_MAN_TANK_CREW,UA_SQUAD,[],UA_VEHICLE_AMMOS],
	["M1135_ATGMV_EP1",UA_MAN_TANK_CREW,UA_SQUAD,[],UA_VEHICLE_AMMOS],
	["M1126_ICV_M2_EP1",UA_MAN_TANK_CREW,UA_SQUAD,[],UA_VEHICLE_AMMOS],
	["M1126_ICV_mk19_EP1",UA_MAN_TANK_CREW,UA_SQUAD,[],UA_VEHICLE_AMMOS]
];

uaHelis = [["AH64D_EP1",UA_MAN_PILOT],["AH6J_EP1",UA_MAN_PILOT],["CH_47F_EP1",UA_MAN_PILOT],["UH60M_EP1",UA_MAN_PILOT]];
uaAir = [["A10_US_EP1",UA_MAN_PILOT],["AV8B2",UA_MAN_PILOT]];

UA_PLAYER_PISTOLS = WPN_NO_SEC+WPN_NO_SEC+[WPN_M9,WPN_M9,WPN_M9SD,WPN_M1911];

uaPLIST = [
	[west,[UA_SOLDIERS,[WPN_M16A4],UA_PLAYER_PISTOLS,WPN_GRENADE_W,UA_AMMOS,UA_GRENS,WPNS_NVG],"US Army Soldier M16A4"],
	[west,[UA_SOLDIERS,[WPN_M4AIM],UA_PLAYER_PISTOLS,WPN_GRENADE_W,UA_AMMOS,UA_GRENS,WPNS_NVG],"US Army Soldier M4 Aimpoint"],
	[west,[UA_SOLDIERS,[WPN_M4A1],UA_PLAYER_PISTOLS,WPN_GRENADE_W,UA_AMMOS,UA_GRENS,WPNS_NVG],"US Army Soldier M4A1"],
	[west,[UA_SOLDIERS,[WPN_M16A2],UA_PLAYER_PISTOLS,WPN_GRENADE_W,UA_AMMOS,UA_GRENS,WPNS_NVG],"US Army Soldier M16A2"],
	[west,[UA_SOLDIERS,[WPN_M14],UA_PLAYER_PISTOLS,WPN_GRENADE_W,UA_AMMOS,UA_GRENS,WPNS_NVG],"US Army Soldier M14 Aimpoint"],
	[west,[UA_SOLDIERS,[WPN_M16A4GL],WPN_NO_SEC,WPN_GRENADE_W,UA_AMMOS,UA_GRENS,WPNS_NVG],"US Army Grenadier M16A4-M203"],
	[west,[UA_SOLDIERS,[WPN_M16A2GL],WPN_NO_SEC,WPN_GRENADE_W,UA_AMMOS,UA_GRENS,WPNS_NVG],"US Army Grenadier M16A2-M203"],
	[west,[UA_SOLDIERS,[WPN_M249],UA_PLAYER_PISTOLS,WPN_GRENADE_W,[4,5],[1,2],WPNS_NVG],"US Army Soldier M249 SAW"],
	[west,[UA_SOLDIERS,[WPN_M249B],UA_PLAYER_PISTOLS,WPN_GRENADE_W,[4,5],[1,2],WPNS_NVG],"US Army Soldier M249 PARA"],
	[west,[UA_SOLDIERS,[WPN_M249SCOPE],UA_PLAYER_PISTOLS,WPN_GRENADE_W,[4,5],[1,2],WPNS_NVG],"US Army Soldier M249 Scope"],
	[west,[UA_SOLDIERS,[WPN_M249TIS],UA_PLAYER_PISTOLS,WPN_GRENADE_W,[4,5],[1,2],WPNS_NVG],"US Army Soldier M249 Thermal Sight"],
	[west,[UA_SOLDIERS,[WPN_M240],UA_PLAYER_PISTOLS,WPN_GRENADE_W,[4,5],[1,2],WPNS_NVG],"US Army Machinegunner M240"],
	[west,[UA_SOLDIERS,[WPN_M240SCOPE],UA_PLAYER_PISTOLS,WPN_GRENADE_W,[4,5],[1,2],WPNS_NVG],"US Army Machinegunner M240 Scope"],
	[west,[UA_SOLDIERS,[WPN_M16A4],[WPN_M136],WPN_GRENADE_W,[4,5],[0,1],WPNS_NVG],"US Army AT Soldier M136"],
	[west,[UA_SOLDIERS,[WPN_M16A4],[WPN_MAAWS],WPN_GRENADE_W,[4,5],[0,1],WPNS_NVG],"US Army AT Soldier MAAWS HEDP"],
	[west,[UA_SOLDIERS,[WPN_M16A4],[WPN_MAAWS2],WPN_GRENADE_W,[4,5],[0,1],WPNS_NVG],"US Army AT Soldier MAAWS HEAT"],
	[west,[UA_SOLDIERS,[WPN_M16A4],[WPN_JAV],WPN_GRENADE_W,[4,5],[0,1],WPNS_NVG],"US Army AT Soldier Javelin"],
	[west,[UA_SOLDIERS,[WPN_M16A4],[WPN_STING],WPN_GRENADE_W,[4,5],[0,1],WPNS_NVG],"US Army AA Soldier Stinger"],
	[west,[["US_Delta_Force_EP1"],[WPN_M17],[WPN_M9],WPN_GRENADE_W,[8],[2,3,4],WPNS_NVG_RF],"Delta Operator Mk17"],
	[west,[["US_Delta_Force_EP1"],[WPN_M17GL],WPN_NO_SEC,WPN_GRENADE_W,[8],[2,3,4],WPNS_NVG_RF],"Delta Operator Mk17 EGLM"],
	[west,[["US_Delta_Force_EP1"],[WPN_M17SNIPER],[WPN_M9],WPN_GRENADE_W,[8],[2,3,4],WPNS_NVG_RF],"Delta Operator Mk17 Sniper"],
	[west,[["US_Delta_Force_EP1"],[WPN_M17SD],[WPN_M9SD],WPN_GRENADE_W,[8],[2,3,4],WPNS_NVG_RF],"Delta Operator Mk17 SD"],
	[west,[["US_Delta_Force_EP1"],[WPN_M17TISSD],[WPN_M9SD],WPN_GRENADE_W,[8],[2,3,4],WPNS_NVG_RF],"Delta Operator Mk17 SD Thermal Sight"],
	[west,[["US_Delta_Force_EP1"],[WPN_M17SNIPERSD],[WPN_M9SD],WPN_GRENADE_W,[8],[2,3,4],WPNS_NVG_RF],"Delta Operator Mk17 Sniper SD"],
	[west,[["US_Soldier_Sniper_EP1"],[WPN_M24DES],[WPN_M9,WPN_PDW],"SmokeShell",[8],[2,3,4],WPNS_NVG_RF],"US Army Sniper M24"],
	[west,[["US_Soldier_Sniper_EP1"],[WPN_M110NV],[WPN_M9,WPN_PDW],"SmokeShell",[8],[2,3,4],WPNS_NVG_RF],"US Army Sniper M110 NV Scope"],
	[west,[["US_Soldier_Sniper_EP1"],[WPN_M110TIS],[WPN_M9,WPN_PDW],"SmokeShell",[8],[2,3,4],WPNS_NVG_RF],"US Army Sniper M110 Thermal Scope"],
	[west,[["US_Soldier_Sniper_EP1"],[WPN_M107],[WPN_M9,WPN_PDW],"SmokeShell",[8],[2,3,4],WPNS_NVG_RF],"US Army Sniper M107"],
	[west,[["US_Soldier_Sniper_EP1"],[WPN_M107TIS],[WPN_M9,WPN_PDW],"SmokeShell",[8],[2,3,4],WPNS_NVG_RF],"US Army Sniper M107 Thermal Scope"]
];

//---- British Army ----
BA_AMMOS = [6,7,8];
BA_GRENS = [2,3,4];
BA_RIFLES = [WPN_SA80SUSAT,WPN_SA80SUSAT,WPN_SA80SUSAT,WPN_SA80SUSAT];
BA_MGS = [WPN_L110,WPN_GPMG];
BA_ATS = [WPN_NLAW,WPN_NLAW,WPN_JAV];
BA_SNIPERRIFLES = [WPN_LRR_DES,WPN_LRR_DES,WPN_LRR_DES,WPN_LRR_DES,WPN_AS50,WPN_AS50TIS];

BA_SOLDIERS = ["BAF_Soldier_MTP"];

BA_MAN = [BA_SOLDIERS,BA_RIFLES+[WPN_SA80UGL,WPN_SA80ACOG,WPN_LSW,WPN_SA80AWS],WPN_NO_SEC,WPN_GRENADE_W,BA_AMMOS,BA_GRENS,WPNS_NVG];
BA_MAN_MG = [BA_SOLDIERS,BA_MGS,WPN_NO_SEC,WPN_GRENADE_W,[5],[2],WPNS_NVG];
BA_MAN_AT = [BA_SOLDIERS,[WPN_SA80SUSAT],BA_ATS,WPN_GRENADE_W,[5],[1],WPNS_NVG];
BA_MAN_MEDIC = [["BAF_Soldier_Medic_MTP"],[WPN_SA80SUSAT],WPN_NO_SEC,"SmokeShell",[5],[3],WPNS_NVG];
BA_MAN_TANK_CREW = [["BAF_crewman_MTP"],[WPN_SA80SUSAT],WPN_NO_SEC,"SmokeShell",BA_AMMOS,BA_GRENS,WPNS_NVG];
BA_MAN_PILOT = [["BAF_Pilot_MTP"],[WPN_SA80SUSAT],WPN_NO_SEC,"SmokeShell",BA_AMMOS,BA_GRENS,WPNS_NVG];
BA_MAN_SNIPER = [["BAF_Soldier_Sniper_MTP"],BA_SNIPERRIFLES,[WPN_M9,WPN_PDW],"SmokeShell",[10],[2],WPNS_NVG_RF];
BA_MAN_SPOTTER = [["BAF_Soldier_Sniper_MTP"],[WPN_SA80UGL,WPN_SA80AWS],WPN_NO_SEC,"SmokeShell",BA_AMMOS,BA_GRENS,WPNS_NVG_RF];

BA_SQUAD = [6,10,
	BA_MAN,BA_MAN,BA_MAN,BA_MAN,BA_MAN,BA_MAN,BA_MAN,BA_MAN,
	BA_MAN_MG,BA_MAN_MG,
	BA_MAN_AT,
	BA_MAN_MEDIC
];
BA_AT_TEAM = [3,5,BA_MAN_AT];

baTeams = [
	BA_SQUAD,BA_SQUAD,BA_SQUAD,BA_SQUAD,
	BA_AT_TEAM
];

baSnipers = [[BA_MAN_SNIPER,BA_MAN_SPOTTER]];

BA_VEHICLE_AMMOS = [
	"30Rnd_556x45_Stanag",
	"handgrenade_west",
	"200Rnd_556x45_L110A1",
	"100Rnd_762x51_M240",
	"1Rnd_HE_M203",
	"NLAW",
	"javelin",
	"stinger",
	"pipebomb",
	"mine",
	"5Rnd_86x70_L115A1",
	"5Rnd_127x99_as50"
];

baCars = [
	["BAF_Offroad_D",BA_MAN,BA_SQUAD,[],BA_VEHICLE_AMMOS],
	["BAF_Jackal2_GMG_D",BA_MAN,BA_SQUAD,[],BA_VEHICLE_AMMOS],
	["BAF_Jackal2_L2A1_D",BA_MAN,BA_SQUAD,[],BA_VEHICLE_AMMOS]
];

baArm = [
	["BAF_FV510_D",BA_MAN_TANK_CREW,BA_SQUAD,[],BA_VEHICLE_AMMOS]
];

baHelis = [["BAF_Apache_AH1_D",BA_MAN_PILOT],["AW159_Lynx_BAF",BA_MAN_PILOT],["BAF_Merlin_HC3_D",BA_MAN_PILOT],["CH_47F_BAF",BA_MAN_PILOT]];

BA_PLAYER_PISTOLS = UA_PLAYER_PISTOLS;

baPLIST = [
	[west,[BA_SOLDIERS,[WPN_SA80SUSAT],BA_PLAYER_PISTOLS,WPN_GRENADE_W,BA_AMMOS,BA_GRENS,WPNS_NVG],"British Army Soldier SA80 SUSAT"],
	[west,[BA_SOLDIERS,[WPN_SA80ACOG],BA_PLAYER_PISTOLS,WPN_GRENADE_W,BA_AMMOS,BA_GRENS,WPNS_NVG],"British Army Soldier SA80 ACOG"],
	[west,[BA_SOLDIERS,[WPN_SA80AWS],BA_PLAYER_PISTOLS,WPN_GRENADE_W,BA_AMMOS,BA_GRENS,WPNS_NVG],"British Army Soldier SA80 Thermal Scope"],
	[west,[BA_SOLDIERS,[WPN_SA80UGL],WPN_NO_SEC,WPN_GRENADE_W,BA_AMMOS,BA_GRENS,WPNS_NVG],"British Army Grenadier SA80 UGL"],
	[west,[BA_SOLDIERS,[WPN_LSW],BA_PLAYER_PISTOLS,WPN_GRENADE_W,BA_AMMOS,BA_GRENS,WPNS_NVG],"British Army Soldier LSW"],
	[west,[BA_SOLDIERS,[WPN_LRR_DES],BA_PLAYER_PISTOLS,WPN_GRENADE_W,BA_AMMOS,BA_GRENS,WPNS_NVG],"British Army Marksman LRR"],
	[west,[BA_SOLDIERS,[WPN_L110],BA_PLAYER_PISTOLS,WPN_GRENADE_W,[4,5],[1,2],WPNS_NVG],"British Army Soldier LMG"],
	[west,[BA_SOLDIERS,[WPN_GPMG],BA_PLAYER_PISTOLS,WPN_GRENADE_W,[4,5],[1,2],WPNS_NVG],"British Army Machinegunner GPMG"],
	[west,[BA_SOLDIERS,[WPN_SA80SUSAT],[WPN_NLAW],WPN_GRENADE_W,[4,5],[0,1],WPNS_NVG],"British Army AT Soldier NLAW"],
	[west,[BA_SOLDIERS,[WPN_SA80SUSAT],[WPN_JAV],WPN_GRENADE_W,[4,5],[0,1],WPNS_NVG],"British Army AT Soldier Javelin"],
	[west,[["BAF_Soldier_Sniper_MTP"],[WPN_LRR_DES],[WPN_M9,WPN_M9SD,WPN_M1911],"SmokeShell",[10],[2],WPNS_NVG_RF],"British Army Sniper LRR"],
	[west,[["BAF_Soldier_Sniper_MTP"],[WPN_AS50],[WPN_M9,WPN_M9SD,WPN_M1911],"SmokeShell",[10],[2],WPNS_NVG_RF],"British Army Sniper AS50"],
	[west,[["BAF_Soldier_Sniper_MTP"],[WPN_AS50TIS],[WPN_M9,WPN_M9SD,WPN_M1911],"SmokeShell",[10],[2],WPNS_NVG_RF],"British Army Sniper AS50 Thermal Scope"]
];

//---- Army of the Czech Republic ----
CZ_AMMOS = [6,7,8];
CZ_GRENS = [2,3,4];
CZ_RIFLES = [WPN_SA58CCO,WPN_SA58CCO,WPN_SA58ACOG];
CZ_RIFLES_NEW = [WPN_CZ805A1,WPN_CZ805A1,WPN_CZ805A1,WPN_CZ805A1GL];
CZ_MGS = [WPN_M249SCOPE,WPN_M60,WPN_UK59];
CZ_ATS = [WPN_RPGL,WPN_MAAWS,WPN_MAAWS2,WPN_JAV];

CZ_SOLDIERS = ["CZ_Soldier_DES_EP1"];

CZ_MAN = [CZ_SOLDIERS,CZ_RIFLES,WPN_NO_SEC,WPN_GRENADE_W,CZ_AMMOS,CZ_GRENS,WPNS_NVG];
CZ_MAN_NEW = [CZ_SOLDIERS,CZ_RIFLES_NEW,WPN_NO_SEC,WPN_GRENADE_W,CZ_AMMOS,CZ_GRENS,WPNS_NVG];
CZ_MAN_MG = [CZ_SOLDIERS,CZ_MGS,WPN_NO_SEC,WPN_GRENADE_W,[5],[1,2],WPNS_NVG];
CZ_MAN_AT = [CZ_SOLDIERS,[WPN_SA58ACOG],CZ_ATS,WPN_GRENADE_W,[5],[1],WPNS_NVG];
CZ_MAN_PILOT = [["CZ_Soldier_Pilot_EP1"],[WPN_SA58V],WPN_NO_SEC,"SmokeShell",CZ_AMMOS,CZ_GRENS,WPNS_NVG];//pilots and crew now have SA58v
CZ_MAN_TANK_CREW = [["CZ_Soldier_Crew_Dst_ACR"],[WPN_SA58V],WPN_NO_SEC,"SmokeShell",CZ_AMMOS,CZ_GRENS,WPNS_NVG];

CZ_MAN_SNIPER = [["CZ_Soldier_Sniper_EP1"],[WPN_CZ750],[WPN_CZ75_P],"SmokeShell",[8],CZ_GRENS,WPNS_NVG_RF];//added acr cz750 sniper rifle
CZ_MAN_SPOTTER = [["CZ_Soldier_Sniper_EP1"],[WPN_CZ805A1GL],WPN_NO_SEC,"SmokeShell",CZ_AMMOS,CZ_GRENS,WPNS_NVG_RF];

DE_MAN_SF = [["GER_Soldier_EP1"],[WPN_G36A_CAMO],WPN_NO_SEC,WPN_GRENADE_W,CZ_AMMOS,CZ_GRENS,WPNS_NVG_RF];//these german sf are included in cz faction
DE_MAN_SF_MG = [["GER_Soldier_EP1"],[WPN_MG36_CAMO],WPN_NO_SEC,WPN_GRENADE_W,[5],[1,2],WPNS_NVG];

CZ_SQUAD = [6,10,//this squad has the older SA58 rifles
	CZ_MAN,CZ_MAN,CZ_MAN,CZ_MAN,CZ_MAN,CZ_MAN,CZ_MAN,CZ_MAN,CZ_MAN,
	CZ_MAN_MG,CZ_MAN_MG,
	CZ_MAN_AT
];
CZ_SQUAD_NEW = [6,10,//this squad uses new CZ850 riflew
	CZ_MAN_NEW,CZ_MAN_NEW,CZ_MAN_NEW,CZ_MAN_NEW,CZ_MAN_NEW,CZ_MAN_NEW,CZ_MAN_NEW,CZ_MAN_NEW,CZ_MAN_NEW,
	CZ_MAN_MG,CZ_MAN_MG,
	CZ_MAN_AT
];

CZ_AT_TEAM = [3,5,CZ_MAN_AT];

DE_SF_TEAM = [4,8,
	DE_MAN_SF,DE_MAN_SF,DE_MAN_SF,
	DE_MAN_SF_MG
];

czTeams = [
	CZ_SQUAD,CZ_SQUAD,CZ_SQUAD,
	CZ_SQUAD_NEW,CZ_SQUAD_NEW,CZ_SQUAD_NEW,
	CZ_AT_TEAM,
	DE_SF_TEAM
];

czSnipers = [[CZ_MAN_SNIPER,CZ_MAN_SPOTTER]];

CZ_VEHICLE_AMMOS = [
	"30Rnd_762x39_AK47",
	"30Rnd_556x45_G36",
	"handgrenade_west",
	"100Rnd_762x51_M240",
	"100Rnd_556x45_M249",
	"100Rnd_762x54_PK",
	"maaws_hedp",
	"maaws_heat",
	"m136",
	"javelin",
	"1Rnd_HE_M203",
	"pipebomb",
	"mine",
	"10Rnd_762x51_CZ750"
];

czCars = [//all cargo squads now have CZ850 rifles
	["LandRover_Special_CZ_EP1",CZ_MAN,CZ_SQUAD_NEW,[],CZ_VEHICLE_AMMOS],
	["LandRover_CZ_EP1",CZ_MAN,CZ_SQUAD_NEW,[],CZ_VEHICLE_AMMOS],
	//ACR cars added (dingo is car not armor for now)
	["Dingo_GL_DST_ACR",CZ_MAN_TANK_CREW,CZ_SQUAD_NEW,[],CZ_VEHICLE_AMMOS],
	["Dingo_DST_ACR",CZ_MAN_TANK_CREW,CZ_SQUAD_NEW,[],CZ_VEHICLE_AMMOS],
	["T810_Des_ACR",CZ_MAN,CZ_SQUAD_NEW,[],CZ_VEHICLE_AMMOS],
	["T810A_Des_MG_ACR",CZ_MAN,CZ_SQUAD_NEW,[],CZ_VEHICLE_AMMOS],
	["T810_Open_Des_ACR",CZ_MAN,CZ_SQUAD_NEW,[],CZ_VEHICLE_AMMOS]
];

czArm = [//ACR armour added
	["BRDM2_Desert_ACR",CZ_MAN_TANK_CREW,CZ_SQUAD_NEW,[],CZ_VEHICLE_AMMOS],
	["Pandur2_ACR",CZ_MAN_TANK_CREW,CZ_SQUAD_NEW,[],CZ_VEHICLE_AMMOS],
	["BMP2_Des_ACR",CZ_MAN_TANK_CREW,CZ_SQUAD_NEW,[],CZ_VEHICLE_AMMOS],
	["T72_ACR",CZ_MAN_TANK_CREW,CZ_SQUAD_NEW,[],[]]
];

czHelis = [
	["Mi24_D_CZ_ACR",CZ_MAN_PILOT],
	["Mi171Sh_rockets_CZ_EP1",CZ_MAN_PILOT],
	["Mi171Sh_CZ_EP1",CZ_MAN_PILOT]
];//added ACR Mi24

czAir = [
	["L159_ACR",CZ_MAN_PILOT],
	["L39_2_ACR",CZ_MAN_PILOT]
];//added ACR L39 and L159

CZ_PLAYER_PISTOLS = WPN_NO_SEC+WPN_NO_SEC+[WPN_CZ75_C,WPN_CZ75_D,WPN_CZ75_P,WPN_CZ75_P_SD];

czPLIST = [
	[west,[CZ_SOLDIERS,[WPN_SA58CCO],CZ_PLAYER_PISTOLS,WPN_GRENADE_W,CZ_AMMOS,CZ_GRENS,WPNS_NVG],"Czech Soldier SA58 CCO"],
	[west,[CZ_SOLDIERS,[WPN_SA58ACOG],CZ_PLAYER_PISTOLS,WPN_GRENADE_W,CZ_AMMOS,CZ_GRENS,WPNS_NVG],"Czech Soldier SA58 ACOG"],
	[west,[CZ_SOLDIERS,[WPN_CZ805A1],CZ_PLAYER_PISTOLS,WPN_GRENADE_W,CZ_AMMOS,CZ_GRENS,WPNS_NVG],"Czech Soldier CZ805 BREN A1"],
	[west,[CZ_SOLDIERS,[WPN_CZ805A1GL],WPN_NO_SEC,WPN_GRENADE_W,CZ_AMMOS,CZ_GRENS,WPNS_NVG],"Czech Soldier CZ805 BREN A1 GL"],
	[west,[CZ_SOLDIERS,[WPN_M249SCOPE],CZ_PLAYER_PISTOLS,WPN_GRENADE_W,[4,5],[1,2],WPNS_NVG],"Czech Solider M249 Scope"],
	[west,[CZ_SOLDIERS,[WPN_UK59],CZ_PLAYER_PISTOLS,WPN_GRENADE_W,[4,5],[1,2],WPNS_NVG],"Czech Machinegunner UK59"],
	[west,[CZ_SOLDIERS,[WPN_M60],CZ_PLAYER_PISTOLS,WPN_GRENADE_W,[4,5],[1,2],WPNS_NVG],"Czech Machinegunner M60"],
	[west,[CZ_SOLDIERS,[WPN_SA58CCO],[WPN_MAAWS],WPN_GRENADE_W,[4,5],[0,1],WPNS_NVG],"Czech AT Soldier MAAWS HEDP"],
	[west,[CZ_SOLDIERS,[WPN_SA58CCO],[WPN_MAAWS2],WPN_GRENADE_W,[4,5],[0,1],WPNS_NVG],"Czech AT Soldier MAAWS HEAT"],
	[west,[CZ_SOLDIERS,[WPN_SA58CCO],[WPN_JAV],WPN_GRENADE_W,[4,5],[0,1],WPNS_NVG],"Czech AT Soldier Javelin"],
	[west,[CZ_SOLDIERS,[WPN_SA58CCO],[WPN_RPGL],WPN_GRENADE_W,[4,5],[0,1],WPNS_NVG],"Czech AT Soldier RPG7"],
	[west,[["CZ_Special_Forces_DES_EP1"],[WPN_M4AIM_SD],CZ_PLAYER_PISTOLS,WPN_GRENADE_W,[8],[2,3,4],WPNS_NVG_RF],"Czech Special Forces M4SD"],
	[west,[["CZ_Soldier_Sniper_EP1"],[WPN_CZ750],CZ_PLAYER_PISTOLS,"SmokeShell",[8],[2,3,4],WPNS_NVG_RF],"Czech Sniper CZ750"],
	[west,[["GER_Soldier_EP1"],[WPN_G36A_CAMO],CZ_PLAYER_PISTOLS,WPN_GRENADE_W,CZ_AMMOS,CZ_GRENS,WPNS_NVG_RF],"German KSK Soldier G36A"],
	[west,[["GER_Soldier_EP1"],[WPN_MG36_CAMO],CZ_PLAYER_PISTOLS,WPN_GRENADE_W,[4,5],[1,2],WPNS_NVG_RF],"German KSK Machinegunner MG36"]
];

//---- Private Military Contractors ----

PM_AMMOS = [8,9,10];//pmc have more ammo and less grenades than regular armies
PM_GRENS = [0,1,2];
PM_RIFLES = [WPN_M4CCO,WPN_M4AIM,WPN_M16A2,WPN_M14,WPN_AKM,WPN_AKS,WPN_FAL,WPN_AK74,WPN_AKS74,WPN_AKSU74,WPN_AKS74PSO,WPN_AKS74KOBRA];// pmc have a wide variety of weapons
PM_MGS = [WPN_PK,WPN_M249,WPN_M240,WPN_M60];
PM_ATS = [WPN_M136,WPN_DRAGON];// gave pmc some at weapons for gameplay reasons, realistically they prob wouldnt have them!
PM_SNIPERRIFLES = [WPN_M107,WPN_M107TIS,WPN_SVD];

PM_SOLDIERS = ["Soldier_M4A3_PMC"];

PM_MAN = [PM_SOLDIERS,PM_RIFLES+[WPN_M16A2GL,WPN_AK74GL],WPN_NO_SEC,WPN_GRENADE_W,PM_AMMOS,PM_GRENS,WPNS_NVG];
PM_MAN_MG = [PM_SOLDIERS,PM_MGS,WPN_NO_SEC,WPN_GRENADE_W,[5],[2],WPNS_NVG];
PM_MAN_AT = [PM_SOLDIERS,PM_RIFLES,PM_ATS,WPN_GRENADE_W,[5],[1],WPNS_NVG];
PM_MAN_PILOT = [["Soldier_Pilot_PMC"],[WPN_M4A1],WPN_NO_SEC,"SmokeShell",PM_AMMOS,PM_GRENS,WPNS_NVG];
PM_MAN_SNIPER = [PM_SOLDIERS,PM_SNIPERRIFLES,[WPN_M9,WPN_PDW],"SmokeShell",[8],PM_GRENS,WPNS_NVG_RF];
PM_MAN_SPOTTER = [PM_SOLDIERS,PM_RIFLES+[WPN_M16A2GL,WPN_AK74GL],WPN_NO_SEC,"SmokeShell",PM_AMMOS,PM_GRENS,WPNS_NVG_RF];

PM_SQUAD = [4,8,
	PM_MAN,PM_MAN,PM_MAN,PM_MAN,
	PM_MAN_MG,
	PM_MAN_AT
];

PMTeams = [PM_SQUAD];//there are no different team types for this faction

pmSnipers = [[PM_MAN_SNIPER,PM_MAN_SPOTTER]];

PM_VEHICLE_AMMOS = [
	"30Rnd_556x45_Stanag",
	"30Rnd_545x39_AK",
	"30Rnd_762x39_AK47",
	"handgrenade_west",
	"200Rnd_556x45_M249",
	"100Rnd_762x51_M240",
	"20Rnd_762x51_FNFAL",
	"100Rnd_762x54_PK",
	"m136",
	"javelin",
	"1Rnd_HE_M203",
	"1Rnd_HE_GP25",
	"pipebomb",
	"mine",
	"10Rnd_127x99_m107",
	"10Rnd_762x54_SVD"
];

pmCars = [["SUV_PMC",PM_MAN,PM_SQUAD,[],7]];

pmArm = [["ArmoredSUV_PMC",PM_MAN,PM_SQUAD,[],7]];

pmHelis = [["Ka60_PMC",PM_MAN_PILOT],["Ka60_GL_PMC",PM_MAN_PILOT],["Ka137_MG_PMC",PM_MAN_PILOT]];

PM_PLAYER_PISTOLS = UA_PLAYER_PISTOLS + CZ_PLAYER_PISTOLS; // added the cz pistols to pmc players for some more variety in the PMC weaapons

pmPLIST = [
	[west,[PM_SOLDIERS,[WPN_M16A2],PM_PLAYER_PISTOLS,WPN_GRENADE_W,PM_AMMOS,PM_GRENS,WPNS_NVG],"Private Contractor M16A2"],
	[west,[PM_SOLDIERS,[WPN_M16A2GL],WPN_NO_SEC,WPN_GRENADE_W,PM_AMMOS,PM_GRENS,WPNS_NVG],"Private Contractor M16A2 M203"],
	[west,[PM_SOLDIERS,[WPN_M4A1],PM_PLAYER_PISTOLS,WPN_GRENADE_W,PM_AMMOS,PM_GRENS,WPNS_NVG],"Private Contractor M4A1"],
	[west,[PM_SOLDIERS,[WPN_M4CCO],PM_PLAYER_PISTOLS,WPN_GRENADE_W,PM_AMMOS,PM_GRENS,WPNS_NVG],"Private Contractor M4A3 CCO"],
	[west,[PM_SOLDIERS,[WPN_M4AIM],PM_PLAYER_PISTOLS,WPN_GRENADE_W,PM_AMMOS,PM_GRENS,WPNS_NVG],"Private Contractor M4A1 Aimpoint"],
	[west,[PM_SOLDIERS,[WPN_M14],PM_PLAYER_PISTOLS,WPN_GRENADE_W,PM_AMMOS,PM_GRENS,WPNS_NVG],"Private Contractor M14 Aimpoint"],
	[west,[PM_SOLDIERS,[WPN_AKM],PM_PLAYER_PISTOLS,WPN_GRENADE_W,PM_AMMOS,PM_GRENS,WPNS_NVG],"Private Contractor AKM"],
	[west,[PM_SOLDIERS,[WPN_AKS],PM_PLAYER_PISTOLS,WPN_GRENADE_W,PM_AMMOS,PM_GRENS,WPNS_NVG],"Private Contractor AKS"],
	[west,[PM_SOLDIERS,[WPN_AKS74],PM_PLAYER_PISTOLS,WPN_GRENADE_W,PM_AMMOS,PM_GRENS,WPNS_NVG],"Private Contractor AKS74"],
	[west,[PM_SOLDIERS,[WPN_AKSU74],PM_PLAYER_PISTOLS,WPN_GRENADE_W,PM_AMMOS,PM_GRENS,WPNS_NVG],"Private Contractor AKSU74"],
	[west,[PM_SOLDIERS,[WPN_AKS74PSO],PM_PLAYER_PISTOLS,WPN_GRENADE_W,PM_AMMOS,PM_GRENS,WPNS_NVG],"Private Contractor AKS74 PSO Scope"],
	[west,[PM_SOLDIERS,[WPN_AKS74KOBRA],PM_PLAYER_PISTOLS,WPN_GRENADE_W,PM_AMMOS,PM_GRENS,WPNS_NVG],"Private Contractor AK74 Kobra"],
	[west,[PM_SOLDIERS,[WPN_AK74GL],WPN_NO_SEC,WPN_GRENADE_W,PM_AMMOS,PM_GRENS,WPNS_NVG],"Private Contractor AK74 GP25"],
	[west,[PM_SOLDIERS,[WPN_FAL],PM_PLAYER_PISTOLS,WPN_GRENADE_W,PM_AMMOS,PM_GRENS,WPNS_NVG],"Private Contractor FN Fal"],
	[west,[PM_SOLDIERS,[WPN_PK],PM_PLAYER_PISTOLS,WPN_GRENADE_W,[4,5],[1,2],WPNS_NVG],"Private Contractor PK"],
	[west,[PM_SOLDIERS,[WPN_M249],PM_PLAYER_PISTOLS,WPN_GRENADE_W,[4,5],[1,2],WPNS_NVG],"Private Contractor M249"],
	[west,[PM_SOLDIERS,[WPN_M240],PM_PLAYER_PISTOLS,WPN_GRENADE_W,[4,5],[1,2],WPNS_NVG],"Private Contractor M240"],
	[west,[PM_SOLDIERS,[WPN_M60],PM_PLAYER_PISTOLS,WPN_GRENADE_W,[4,5],[1,2],WPNS_NVG],"Private Contractor M60"],
	[west,[PM_SOLDIERS,[WPN_M4AIM],[WPN_M136],WPN_GRENADE_W,[4,5],[0,1],WPNS_NVG],"Private Contractor M136"],
	[west,[PM_SOLDIERS,[WPN_M4AIM],[WPN_DRAGON],WPN_GRENADE_W,[4,5],[0,1],WPNS_NVG],"Private Contractor Dragon"],
	[west,[PM_SOLDIERS,[WPN_SVD],PM_PLAYER_PISTOLS,"SmokeShell",[8],[2,3,4],WPNS_NVG_BINO],"Private Contractor SVD"],
	[west,[PM_SOLDIERS,[WPN_M107],PM_PLAYER_PISTOLS,"SmokeShell",[8],[2,3,4],WPNS_NVG_BINO],"Private Contractor M107"],
	[west,[PM_SOLDIERS,[WPN_M107TIS],PM_PLAYER_PISTOLS,"SmokeShell",[8],[2,3,4],WPNS_NVG_BINO],"Private Contractor M107 Thermal Scope"]
];

//---- Takistan Army ----

TA_AMMOS = [4,5,6,7,8];
TA_GRENS = [0,1,2,3,4];
TA_SF_AMMOS = [6,7,8];
TA_SF_GRENS = [2,3,4];

TA_RIFLES = [WPN_AK74,WPN_AK74,WPN_AK74,WPN_AKS74];
TA_MGS = [WPN_RPK,WPN_PK,WPN_PK];
TA_ATS = [WPN_RPGL,WPN_RPGR,WPN_RPGO,WPN_AT13];
TA_SNIPERRIFLES = [WPN_SVD_CAMO_DES,WPN_SVD_CAMO_DES,WPN_SVD_NPSU];

TA_SOLDIERS = ["TK_Soldier_EP1"];

TA_MAN = [TA_SOLDIERS,TA_RIFLES + [WPN_AKS74PSO,WPN_SVD,WPN_AK74GL,WPN_AK74GL],WPN_NO_SEC,WPN_GRENADE_E,TA_AMMOS,TA_GRENS,[]];
TA_MAN_AT = [TA_SOLDIERS,TA_RIFLES,TA_ATS,WPN_NO_GREN,[4,5,6],[0],[]];
TA_MAN_MG = [TA_SOLDIERS,TA_MGS,WPN_NO_SEC,WPN_GRENADE_E,[4,5],[0,1,2],[]];
TA_MAN_MEDIC = [["TK_Soldier_Medic_EP1"],[WPN_AKS74,WPN_AKSU74],WPN_NO_SEC,"SmokeShell",[4,5],[0,1,2,3],[]];
TA_MAN_AA = [TA_SOLDIERS,TA_RIFLES,[WPN_STRELA],WPN_GRENADE_E,[4,5],[0,1],WPNS_BINO];
TA_MAN_TANK_CREW = [["TK_Soldier_Crew_EP1"],[WPN_AKSU74],WPN_NO_SEC,"SmokeShell",TA_AMMOS,TA_GRENS,WPNS_NVG];
TA_MAN_DRIVER = [["TK_Soldier_EP1"],[WPN_AKSU74],WPN_NO_SEC,"SmokeShell",TA_AMMOS,TA_GRENS,[]];
TA_MAN_PILOT = [["TK_Soldier_Pilot_EP1"],[WPN_AKSU74],WPN_NO_SEC,"SmokeShell",TA_AMMOS,TA_GRENS,WPNS_NVG];
TA_MAN_SNIPER = [["TK_Soldier_Sniper_EP1"],TA_SNIPERRIFLES,[WPN_MAKAROV,WPN_MAKAROV_SD,WPN_SKORPION],"SmokeShell",TA_AMMOS,TA_GRENS,WPNS_NVG_BINO];
TA_MAN_SPOTTER = [["TK_Soldier_Sniper_EP1"],[WPN_AK74,WPN_AK74GL,WPN_AKS74PSO],WPN_NO_SEC,"SmokeShell",TA_AMMOS,TA_GRENS,WPNS_NVG_BINO];
TA_MAN_SF = [["TK_Special_Forces_EP1"],[WPN_AKS74,WPN_AK74GL,WPN_AKS74PSO,WPN_AKSU74,WPN_AKS74_TIS,WPN_SVD],[WPN_MAKAROV,WPN_MAKAROV_SD,WPN_SKORPION],WPN_GRENADE_E,TA_SF_AMMOS,TA_SF_GRENS,WPNS_NVG_BINO];
TA_MAN_SF_AT = [["TK_Special_Forces_EP1"],[WPN_AKS74,WPN_AKSU74],TA_ATS,WPN_NO_GREN,[5,6],[0],WPNS_NVG];
TA_MAN_SF_MG = [["TK_Special_Forces_EP1"],[WPN_PK],[WPN_MAKAROV,WPN_MAKAROV_SD],WPN_GRENADE_E,[5],[1,2],WPNS_NVG];

TA_SQUAD = [6,10,
	TA_MAN,TA_MAN,TA_MAN,TA_MAN,TA_MAN,TA_MAN,TA_MAN,//added 2 more standard soldiers (squads were a bit over armed)
	TA_MAN_MG,TA_MAN_MG,
	TA_MAN_AT,
	TA_MAN_AA,
	TA_MAN_MEDIC
];
TA_SECTION = [4,6,
	TA_MAN,TA_MAN,TA_MAN,TA_MAN,
	TA_MAN_MG
];
TA_AT_TEAM = [2,4,TA_MAN_AT];
TA_SF_TEAM = [4,10,
	TA_MAN_SF,TA_MAN_SF,TA_MAN_SF,
	TA_MAN_SF_AT,
	TA_MAN_SF_MG
];

taTeams = [
	TA_SQUAD,TA_SQUAD,TA_SQUAD,TA_SQUAD,//added more squad and section to reduce number of SF groups a bit
	TA_SECTION,TA_SECTION,
	TA_AT_TEAM,
	TA_SF_TEAM
];

taSnipers = [[TA_MAN_SNIPER,TA_MAN_SPOTTER]];

TA_VAEHICLE_AMMOS = [
	"30Rnd_545x39_AK",
	"handgrenade_east",
	"100Rnd_762x54_PK",
	"75Rnd_545x39_RPK",
	"PG7VL",
	"PG7VR",
	"OG7",
	"pipebomb",
	"at13",
	"Strela",
	"minee",
	"10Rnd_762x54_SVD",
	"1Rnd_HE_GP25"
];

taCars = [
	["LandRover_MG_TK_EP1",TA_MAN_DRIVER,TA_SQUAD,[],TA_VAEHICLE_AMMOS],
	["LandRover_SPG9_TK_EP1",TA_MAN_DRIVER,TA_SQUAD,[],TA_VAEHICLE_AMMOS],
	["UAZ_Unarmed_TK_EP1",TA_MAN_DRIVER,TA_SQUAD,[],TA_VAEHICLE_AMMOS],
	["UAZ_MG_TK_EP1",TA_MAN_DRIVER,TA_SQUAD,[],TA_VAEHICLE_AMMOS],
	["UAZ_AGS30_TK_EP1",TA_MAN_DRIVER,TA_SQUAD,[],TA_VAEHICLE_AMMOS],
	["Ural_ZU23_TK_EP1",TA_MAN_DRIVER,TA_SQUAD,[],TA_VAEHICLE_AMMOS],
	["V3S_Open_TK_EP1",TA_MAN_DRIVER,TA_SQUAD,[],TA_VAEHICLE_AMMOS],
	["V3S_TK_EP1",TA_MAN_DRIVER,TA_SQUAD,[],TA_VAEHICLE_AMMOS]
];

taArm = [
	["T72_TK_EP1",TA_MAN_TANK_CREW,TA_SQUAD,[],[]],
	["T55_TK_EP1",TA_MAN_TANK_CREW,TA_SQUAD,[],[]],
	["BVP1_TK_ACR",TA_MAN_TANK_CREW,TA_SQUAD,[],TA_VAEHICLE_AMMOS],//added ACR BMP1, replaced t34
	["BMP2_TK_EP1",TA_MAN_TANK_CREW,TA_SQUAD,[],TA_VAEHICLE_AMMOS],
	["BTR60_TK_EP1",TA_MAN_TANK_CREW,TA_SQUAD,[],TA_VAEHICLE_AMMOS],
	["BRDM2_TK_EP1",TA_MAN_TANK_CREW,TA_SQUAD,[],TA_VAEHICLE_AMMOS],
	["M113_TK_EP1",TA_MAN_TANK_CREW,TA_SQUAD,[],TA_VAEHICLE_AMMOS],
	["ZSU_TK_EP1",TA_MAN_TANK_CREW,TA_SQUAD,[],[]]
];

taHelis = [["Mi24_D_TK_EP1",TA_MAN_PILOT],["Mi17_TK_EP1",TA_MAN_PILOT],["UH1H_TK_EP1",TA_MAN_PILOT]];

taAir = [["Su25_TK_EP1",TA_MAN_PILOT]];//removed Taki L39 (su25 more reaslistic for Takis, and ACR now have L39) ,["L39_TK_EP1",TA_MAN_PILOT]];

TA_PLAYER_PISTOLS = WPN_NO_SEC+WPN_NO_SEC+[WPN_MAKAROV,WPN_MAKAROV,WPN_MAKAROV_SD,WPN_SKORPION];

taPLIST = [
	[east,[TA_SOLDIERS,[WPN_AK74],TA_PLAYER_PISTOLS,WPN_GRENADE_E,TA_AMMOS,TA_GRENS,[]],"Takistani Army Soldier AK74"],
	[east,[TA_SOLDIERS,[WPN_AK74GL],WPN_NO_SEC,WPN_GRENADE_E,TA_AMMOS,TA_GRENS,[]],"Takistani Army Grenadier AK74 GP25"],
	[east,[TA_SOLDIERS,[WPN_AKS74],TA_PLAYER_PISTOLS,WPN_GRENADE_E,TA_AMMOS,TA_GRENS,[]],"Takistani Army Soldier AKS74"],
	[east,[TA_SOLDIERS,[WPN_AKSU74],TA_PLAYER_PISTOLS,WPN_GRENADE_E,TA_AMMOS,TA_GRENS,[]],"Takistani Army Soldier AKSU74"],
	[east,[TA_SOLDIERS,[WPN_AKS74PSO],TA_PLAYER_PISTOLS,WPN_GRENADE_E,TA_AMMOS,TA_GRENS,[]],"Takistani Army Soldier AK74 PSO Scope"],
	[east,[TA_SOLDIERS,[WPN_AKS74_NSPU],TA_PLAYER_PISTOLS,WPN_GRENADE_E,TA_AMMOS,TA_GRENS,[]],"Takistani Army Soldier AKS74 Night Scope"],
	[east,[TA_SOLDIERS,[WPN_AKS74_TIS],TA_PLAYER_PISTOLS,WPN_GRENADE_E,TA_AMMOS,TA_GRENS,[]],"Takistani Army Soldier AKS74 Thermal Scope"],
	[east,[TA_SOLDIERS,[WPN_SVD],TA_PLAYER_PISTOLS,WPN_GRENADE_E,TA_AMMOS,TA_GRENS,WPNS_BINO],"Takistani Army Marksman SVD"],
	[east,[TA_SOLDIERS,[WPN_SVD_NPSU],TA_PLAYER_PISTOLS,WPN_GRENADE_E,TA_AMMOS,TA_GRENS,WPNS_BINO],"Takistani Army Marksman SVD Night Scope"],
	[east,[TA_SOLDIERS,[WPN_PK],TA_PLAYER_PISTOLS,WPN_GRENADE_E,[4,5],[0,1,2],[]],"Takistani Army Machinegunner PK"],
	[east,[TA_SOLDIERS,[WPN_RPK],TA_PLAYER_PISTOLS,WPN_GRENADE_E,[4,5],[0,1,2],[]],"Takistani Army Machinegunner RPK"],
	[east,[TA_SOLDIERS,[WPN_AKS74],[WPN_RPGL],WPN_GRENADE_E,[4,5,6],[0],[]],"Takistani AT Soldier RPG7"],
	[east,[TA_SOLDIERS,[WPN_AKS74],[WPN_AT13],WPN_GRENADE_E,[4,5,6],[0],[]],"Takistani AT Soldier AT13"],
	[east,[["TK_Soldier_Sniper_EP1"],[WPN_SVD_CAMO_DES],TA_PLAYER_PISTOLS,"SmokeShell",[8],[2,3,4],WPNS_BINO],"Takistani Army Sniper SVD"],
	[east,[["TK_Soldier_Sniper_EP1"],[WPN_SVD_NPSU],TA_PLAYER_PISTOLS,"SmokeShell",[8],[2,3,4],WPNS_BINO],"Takistani Army Sniper SVD Night Scope"],
	[east,[["TK_Special_Forces_EP1"],[WPN_AKS74],TA_PLAYER_PISTOLS,WPN_GRENADE_E,TA_SF_AMMOS,TA_SF_GRENS,WPNS_NVG_BINO],"Takistani Special Forces AKS74"],
	[east,[["TK_Special_Forces_EP1"],[WPN_AK74GL],WPN_NO_SEC,WPN_GRENADE_E,TA_SF_AMMOS,TA_SF_GRENS,WPNS_NVG_BINO],"Takistani Special Forces AK74 GP25"],
	[east,[["TK_Special_Forces_EP1"],[WPN_AKS74PSO],TA_PLAYER_PISTOLS,WPN_GRENADE_E,TA_SF_AMMOS,TA_SF_GRENS,WPNS_NVG_BINO],"Takistani Special Forces AKS74 PSO Scope"],
	[east,[["TK_Special_Forces_EP1"],[WPN_AKSU74],TA_PLAYER_PISTOLS,WPN_GRENADE_E,TA_SF_AMMOS,TA_SF_GRENS,WPNS_NVG_BINO],"Takistani Special Forces AKSU74"],
	[east,[["TK_Special_Forces_EP1"],[WPN_AKS74],[WPN_RPGL],WPN_GRENADE_E,[5],[1],WPNS_NVG_BINO],"Takistani Special Forces RPG7"],
	[east,[["TK_Special_Forces_EP1"],[WPN_PK],TA_PLAYER_PISTOLS,WPN_GRENADE_E,[5],[1,2],WPNS_NVG_BINO],"Takistani Special Forces PK"],
	[east,[["TK_Special_Forces_EP1"],[WPN_AKS74_NSPU],TA_PLAYER_PISTOLS,WPN_GRENADE_E,TA_SF_AMMOS,TA_SF_GRENS,WPNS_NVG_BINO],"Takistani Special Forces AKS74 Night Scope"],
	[east,[["TK_Special_Forces_EP1"],[WPN_AKS74_TIS],TA_PLAYER_PISTOLS,WPN_GRENADE_E,TA_SF_AMMOS,TA_SF_GRENS,WPNS_NVG_BINO],"Takistani Special Forces AKS74 Thermal Scope"],
	[east,[["TK_Special_Forces_EP1"],[WPN_SVD],TA_PLAYER_PISTOLS,WPN_GRENADE_E,TA_SF_AMMOS,TA_SF_GRENS,WPNS_NVG_BINO],"Takistani Special Forces SVD"],
	[east,[["TK_Special_Forces_EP1"],[WPN_SVD_NPSU],TA_PLAYER_PISTOLS,WPN_GRENADE_E,TA_SF_AMMOS,TA_SF_GRENS,WPNS_NVG_BINO],"Takistani Special Forces SVD Night Scope"]
];

//---- Taliban ----

//milita forces
TM_AMMOS = [4,5,6];
TM_GRENS = [0,1,2,3];

TM_RIFLES = [
	WPN_AKM,WPN_AKM,WPN_AKM,WPN_AKM,
	WPN_AKS,WPN_AKS,
	WPN_AK74,WPN_AKS74,
	WPN_LEE,
	WPN_FAL,WPN_FAL
];

TM_MGS = [WPN_RPK,WPN_PK,WPN_PK];

TM_ATS = [WPN_RPG,WPN_RPGL,WPN_RPGR,WPN_RPGO];

TM_SOLDIERS = ["TK_INS_Soldier_EP1","TK_INS_Soldier_2_EP1","TK_INS_Soldier_3_EP1","TK_INS_Soldier_4_EP1","TK_INS_Soldier_TL_EP1"];

TM_MAN = [TM_SOLDIERS,TM_RIFLES + TM_RIFLES + [WPN_AKS74PSO,WPN_SVD,WPN_AK74GL],WPN_NO_SEC,WPN_GRENADE_E,TM_AMMOS,TM_GRENS,[]];
TM_MAN_AT = [TM_SOLDIERS,TM_RIFLES,TM_ATS,WPN_NO_GREN,TM_AMMOS,TM_GRENS,[]];
TM_MAN_MG = [TM_SOLDIERS,TM_MGS,WPN_NO_SEC,WPN_GRENADE_E,[3,4,5],[0,1,2],[]];
TM_MAN_MEDIC = [["TK_INS_Bonesetter_EP1"],TM_RIFLES,WPN_NO_SEC,WPN_NO_GREN,TM_AMMOS,TM_GRENS,[]];
TM_MAN_AA = [TM_SOLDIERS,TM_RIFLES,[WPN_STRELA],WPN_NO_GREN,TM_AMMOS,[0],WPNS_BINO];
TM_MAN_SNIPER = [TM_SOLDIERS,[WPN_SVD],WPN_NO_SEC,"smokeShell",TM_AMMOS,TM_GRENS,WPNS_BINO];

TM_SQUAD = [4,10,
	TM_MAN,TM_MAN,TM_MAN,TM_MAN,TM_MAN,TM_MAN,TM_MAN,TM_MAN,
	TM_MAN_AT,TM_MAN_AT,
	TM_MAN_MG,TM_MAN_MG,
	TM_MAN_AA,
	TM_MAN_MEDIC
];
TM_SECTION = [2,6,TM_MAN];
TM_AT_TEAM = [2,3,TM_MAN_AT];

//guerilla forces
TG_AMMOS = [4,5,6];
TG_GRENS = [0,1,2];

TG_RIFLES = [
	WPN_AKM,WPN_AKM,WPN_AKM,WPN_AKM,WPN_AKM,WPN_AKM,
	WPN_AKS,WPN_AKS,
	WPN_LEE,WPN_LEE,WPN_LEE,WPN_LEE
];
TG_MGS = [WPN_RPK,WPN_PK,WPN_PK];
TG_ATS = [WPN_RPG,WPN_RPGL,WPN_RPGR,WPN_RPGO,WPN_DRAGON];

TG_SOLDIERS = ["TK_GUE_Soldier_ep1","TK_GUE_Soldier_2_ep1","TK_GUE_Soldier_4_ep1","TK_GUE_Soldier_5_ep1","TK_GUE_Soldier_AR_ep1"];

TG_MAN = [TG_SOLDIERS,TG_RIFLES + TG_RIFLES + [WPN_SVD],WPN_NO_SEC,WPN_GRENADE_E,TG_AMMOS,TG_GRENS,[]];
TG_MAN_AT = [TG_SOLDIERS,TG_RIFLES,TG_ATS,WPN_NO_GREN,TG_AMMOS,TG_GRENS,[]];
TG_MAN_MG = [TG_SOLDIERS,TG_MGS,WPN_NO_SEC,WPN_GRENADE_E,[3,4,5],[0,1,2],[]];
TG_MAN_MEDIC = [["TK_GUE_Bonesetter_ep1"],TG_RIFLES,WPN_NO_SEC,WPN_NO_GREN,TG_AMMOS,TG_GRENS,[]];
TG_MAN_AA = [TG_SOLDIERS,TG_RIFLES,[WPN_STING],WPN_NO_GREN,TG_AMMOS,[0],[]];
TG_MAN_SNIPER = [TG_SOLDIERS,[WPN_SVD],WPN_NO_SEC,"smokeShell",TG_AMMOS,TG_GRENS,WPNS_BINO];

TG_SQUAD = [4,10,
	TG_MAN,TG_MAN,TG_MAN,TG_MAN,TG_MAN,TG_MAN,TG_MAN,TG_MAN,
	TG_MAN_AT,TG_MAN_AT,
	TG_MAN_MG,TG_MAN_MG,
	TG_MAN_AA,
	TG_MAN_MEDIC
];
TG_SECTION = [2,6,TG_MAN];
TG_AT_TEAM = [2,3,TG_MAN_AT];

tmTeams = [
	TM_SQUAD,TM_SQUAD,TM_SQUAD,TM_SQUAD,
	TM_SECTION,TM_SECTION,
	TM_AT_TEAM,
	TG_SQUAD,TG_SQUAD,TG_SQUAD,TG_SQUAD,
	TG_SECTION,TG_SECTION,
	TG_AT_TEAM
];

tmSnipers = [[TM_MAN_SNIPER,TM_MAN],[TG_MAN_SNIPER,TG_MAN]];

TM_VAEHICLE_AMMOS = [
	"30Rnd_762x39_AK47",
	"30Rnd_545x39_AK",
	"10x_303",
	"handgrenade_east",
	"100Rnd_762x54_PK",
	"75Rnd_545x39_RPK",
	"PG7VL",
	"PG7VR",
	"OG7",
	"pipebomb",
	"Strela",
	"minee",
	"10Rnd_762x54_SVD",
	"1Rnd_HE_GP25"
];

tmCars = [
	["LandRover_SPG9_TK_INS_EP1",TM_MAN,TM_SQUAD,[],TM_VAEHICLE_AMMOS],
	["LandRover_MG_TK_INS_EP1",TM_MAN,TM_SQUAD,[],TM_VAEHICLE_AMMOS],
	["Lada1_TK_CIV_EP1",TG_MAN,TG_SQUAD,[],TM_VAEHICLE_AMMOS],
	["Lada2_TK_CIV_EP1",TG_MAN,TG_SQUAD,[],TM_VAEHICLE_AMMOS],
	["UAZ_MG_TK_EP1",TM_MAN,TM_SQUAD,[],TM_VAEHICLE_AMMOS],
	["Old_moto_TK_Civ_EP1",TG_MAN,TG_SQUAD,[],TM_VAEHICLE_AMMOS],
	["UAZ_Unarmed_TK_CIV_EP1",TM_MAN,TM_SQUAD,[],TM_VAEHICLE_AMMOS],
	["Volha_1_TK_CIV_EP1",TG_MAN,TG_SQUAD,[],TM_VAEHICLE_AMMOS],
	["Volha_2_TK_CIV_EP1",TG_MAN,TG_SQUAD,[],TM_VAEHICLE_AMMOS]
];

tmArm = [
	["BVP1_TK_ACR",TM_MAN,TM_SQUAD,[],TM_VAEHICLE_AMMOS],	//added ACR BMP1
	["BTR40_TK_INS_EP1",TM_MAN,TM_SQUAD,[],TM_VAEHICLE_AMMOS],
	["BTR40_MG_TK_INS_EP1",TM_MAN,TM_SQUAD,[],TM_VAEHICLE_AMMOS],
	["BMP2_TK_EP1",TM_MAN,TM_SQUAD,[],TM_VAEHICLE_AMMOS],
	["BTR60_TK_EP1",TM_MAN,TM_SQUAD,[],TM_VAEHICLE_AMMOS],
	["BRDM2_TK_EP1",TM_MAN,TM_SQUAD,[],TM_VAEHICLE_AMMOS],
	["T55_TK_EP1",TM_MAN,TM_SQUAD,[],[]],
	["T34_TK_EP1",TM_MAN,TM_SQUAD,[],[]]
];

TM_PLAYER_PISTOLS = WPN_NO_SEC+WPN_NO_SEC+[WPN_MAKAROV,WPN_MAKAROV,WPN_MAKAROV_SD,WPN_M1911];

tmPLIST = [
	[east,[TM_SOLDIERS+TG_SOLDIERS,[WPN_AKM],TM_PLAYER_PISTOLS,WPN_GRENADE_E,TM_AMMOS,TM_GRENS,[]],"Taliban Soldier AKM"],
	[east,[TM_SOLDIERS+TG_SOLDIERS,[WPN_AKS],TM_PLAYER_PISTOLS,WPN_GRENADE_E,TM_AMMOS,TM_GRENS,[]],"Taliban Soldier AKS"],
	[east,[TM_SOLDIERS+TG_SOLDIERS,[WPN_AK74],TM_PLAYER_PISTOLS,WPN_GRENADE_E,TM_AMMOS,TM_GRENS,[]],"Taliban Soldier AK74"],
	[east,[TM_SOLDIERS+TG_SOLDIERS,[WPN_AKS74],TM_PLAYER_PISTOLS,WPN_GRENADE_E,TM_AMMOS,TM_GRENS,[]],"Taliban Soldier AKS74"],
	[east,[TM_SOLDIERS+TG_SOLDIERS,[WPN_LEE],TM_PLAYER_PISTOLS,WPN_GRENADE_E,TM_AMMOS,TM_GRENS,WPNS_BINO],"Taliban Soldier Lee Enfield"],
	[east,[TM_SOLDIERS+TG_SOLDIERS,[WPN_FAL],TM_PLAYER_PISTOLS,WPN_GRENADE_E,TM_AMMOS,TM_GRENS,[]],"Taliban Soldier FN Fal"],
	[east,[TM_SOLDIERS+TG_SOLDIERS,[WPN_AKM],[WPN_RPG],WPN_GRENADE_E,[3,4,5],[0,0,1],[]],"Taliban AT Soldier RPG7"],
	[east,[TM_SOLDIERS+TG_SOLDIERS,[WPN_RPK],TM_PLAYER_PISTOLS,WPN_GRENADE_E,[2,3,4],[0,1,2],[]],"Taliban Machinegunner RPK"],
	[east,[TM_SOLDIERS+TG_SOLDIERS,[WPN_PK],TM_PLAYER_PISTOLS,WPN_GRENADE_E,[2,3,4],[0,1,2],[]],"Taliban Machinegunner PK"],
	[east,[TM_SOLDIERS+TG_SOLDIERS,[WPN_SVD],TM_PLAYER_PISTOLS,WPN_GRENADE_E,TM_AMMOS,TM_GRENS,WPNS_BINO],"Taliban Sniper SVD"]
];

//---- Civilian Players ---- (only used in select player dialog, never randomly chosen)
cvPLIST = [];
cvPLIST = cvPLIST + [[civilian,[["Haris_Press_EP1"]],"Civilian News Reporter"]];
cvPLIST = cvPLIST + [[civilian,[["TK_CIV_Takistani01_EP1","TK_CIV_Takistani02_EP1","TK_CIV_Takistani03_EP1","TK_CIV_Takistani04_EP1","TK_CIV_Takistani05_EP1","TK_CIV_Takistani06_EP1","TK_CIV_Worker01_EP1"]],"Takistani civilian man"]];
cvPLIST = cvPLIST + [[civilian,[["TK_CIV_Woman01_EP1","TK_CIV_Woman02_EP1","TK_CIV_Woman03_EP1"]],"Takistani civilian woman"]];
ALL_PLIST = ALL_PLIST + cvPLIST;//puts the civ players on players list in setup dialog (needed as they are not added as a faction)

//---- Factions setup ----
// each faction must have 9 elements in this format:
// [side,nameString,infantry,snipers,cars,armor,helis,aircraft,players];
// the order you add them = their order on the setup screen
// the variable names (e.g. "USMC_FACTION") are used in Presets (e.g. "Insurgency") to set specific factions
USARMY_FACTION = [west,"US Army",uaTeams,uaSnipers,uaCars,uaArm,uaHelis,uaAir,uaPLIST] call addFaction;
BRIT_FACTION = [west,"British Army",baTeams,baSnipers,baCars,baArm,baHelis,uaAir,baPLIST] call addFaction;//BAF have US air suport
CZECH_FACTION = [west,"Czech Army",czTeams,czSnipers,czCars,czArm,czHelis,czAir,czPLIST] call addFaction;
PMC_FACTION = [west,"Private Contractors",pmTeams,pmSnipers,pmCars,pmArm,pmHelis,[],pmPLIST] call addFaction;//PMC have no air support
TAKI_FACTION = [east,"Takistan Army",taTeams,taSnipers,taCars,taArm,taHelis,[],taPLIST] call addFaction;
TALIBAN_FACTION = [east,"Taliban",tmTeams,tmSnipers,tmCars,tmArm,[],[],tmPLIST] call addFaction;//Taliban have no helis or air

